"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useSchedule = exports.ScheduleProvider = exports.nextStartAt = exports.currentEndAt = exports.currentStartAt = exports.getNextScheduleEntry = exports.getCurrentScheduleEntry = exports.hasContestStarted = exports.isInContest = exports.fetchSchedule = void 0;
var feature_1 = require("./feature");
Object.defineProperty(exports, "fetchSchedule", { enumerable: true, get: function () { return feature_1.fetchSchedule; } });
Object.defineProperty(exports, "isInContest", { enumerable: true, get: function () { return feature_1.isInContest; } });
Object.defineProperty(exports, "hasContestStarted", { enumerable: true, get: function () { return feature_1.hasContestStarted; } });
Object.defineProperty(exports, "getCurrentScheduleEntry", { enumerable: true, get: function () { return feature_1.getCurrentScheduleEntry; } });
Object.defineProperty(exports, "getNextScheduleEntry", { enumerable: true, get: function () { return feature_1.getNextScheduleEntry; } });
Object.defineProperty(exports, "currentStartAt", { enumerable: true, get: function () { return feature_1.currentStartAt; } });
Object.defineProperty(exports, "currentEndAt", { enumerable: true, get: function () { return feature_1.currentEndAt; } });
Object.defineProperty(exports, "nextStartAt", { enumerable: true, get: function () { return feature_1.nextStartAt; } });
var provider_1 = require("./provider");
Object.defineProperty(exports, "ScheduleProvider", { enumerable: true, get: function () { return provider_1.ScheduleProvider; } });
var use_schedule_1 = require("./use-schedule");
Object.defineProperty(exports, "useSchedule", { enumerable: true, get: function () { return use_schedule_1.useSchedule; } });
