/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/~__root";
import { Route as TeamsRouteImport } from "./routes/~teams";
import { Route as SignupRouteImport } from "./routes/~signup";
import { Route as SigninRouteImport } from "./routes/~signin";
import { Route as RuleRouteImport } from "./routes/~rule";
import { Route as RankingRouteImport } from "./routes/~ranking";
import { Route as ProblemsRouteImport } from "./routes/~problems";
import { Route as AnnouncesRouteImport } from "./routes/~announces";
import { Route as ActivityRouteImport } from "./routes/~activity";
import { Route as IndexRouteImport } from "./routes/~index";
import { Route as SigninIndexRouteImport } from "./routes/~signin.index";
import { Route as ProblemsIndexRouteImport } from "./routes/~problems.index";
import { Route as AnnouncesIndexRouteImport } from "./routes/~announces.index";
import { Route as SigninImpersonationRouteImport } from "./routes/~signin.impersonation";
import { Route as ProblemsCodeRouteImport } from "./routes/~problems.$code";
import { Route as AnnouncesSlugRouteImport } from "./routes/~announces.$slug";

const TeamsRoute = TeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const RuleRoute = RuleRouteImport.update({
  id: "/rule",
  path: "/rule",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/~rule.lazy").then((d) => d.Route));
const RankingRoute = RankingRouteImport.update({
  id: "/ranking",
  path: "/ranking",
  getParentRoute: () => rootRouteImport,
} as any);
const ProblemsRoute = ProblemsRouteImport.update({
  id: "/problems",
  path: "/problems",
  getParentRoute: () => rootRouteImport,
} as any);
const AnnouncesRoute = AnnouncesRouteImport.update({
  id: "/announces",
  path: "/announces",
  getParentRoute: () => rootRouteImport,
} as any);
const ActivityRoute = ActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SigninRoute,
} as any);
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProblemsRoute,
} as any);
const AnnouncesIndexRoute = AnnouncesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AnnouncesRoute,
} as any);
const SigninImpersonationRoute = SigninImpersonationRouteImport.update({
  id: "/impersonation",
  path: "/impersonation",
  getParentRoute: () => SigninRoute,
} as any);
const ProblemsCodeRoute = ProblemsCodeRouteImport.update({
  id: "/$code",
  path: "/$code",
  getParentRoute: () => ProblemsRoute,
} as any).lazy(() =>
  import("./routes/~problems.$code.lazy").then((d) => d.Route),
);
const AnnouncesSlugRoute = AnnouncesSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => AnnouncesRoute,
} as any).lazy(() =>
  import("./routes/~announces.$slug.lazy").then((d) => d.Route),
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/activity": typeof ActivityRoute;
  "/announces": typeof AnnouncesRouteWithChildren;
  "/problems": typeof ProblemsRouteWithChildren;
  "/ranking": typeof RankingRoute;
  "/rule": typeof RuleRoute;
  "/signin": typeof SigninRouteWithChildren;
  "/signup": typeof SignupRoute;
  "/teams": typeof TeamsRoute;
  "/announces/$slug": typeof AnnouncesSlugRoute;
  "/problems/$code": typeof ProblemsCodeRoute;
  "/signin/impersonation": typeof SigninImpersonationRoute;
  "/announces/": typeof AnnouncesIndexRoute;
  "/problems/": typeof ProblemsIndexRoute;
  "/signin/": typeof SigninIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/activity": typeof ActivityRoute;
  "/ranking": typeof RankingRoute;
  "/rule": typeof RuleRoute;
  "/signup": typeof SignupRoute;
  "/teams": typeof TeamsRoute;
  "/announces/$slug": typeof AnnouncesSlugRoute;
  "/problems/$code": typeof ProblemsCodeRoute;
  "/signin/impersonation": typeof SigninImpersonationRoute;
  "/announces": typeof AnnouncesIndexRoute;
  "/problems": typeof ProblemsIndexRoute;
  "/signin": typeof SigninIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/activity": typeof ActivityRoute;
  "/announces": typeof AnnouncesRouteWithChildren;
  "/problems": typeof ProblemsRouteWithChildren;
  "/ranking": typeof RankingRoute;
  "/rule": typeof RuleRoute;
  "/signin": typeof SigninRouteWithChildren;
  "/signup": typeof SignupRoute;
  "/teams": typeof TeamsRoute;
  "/announces/$slug": typeof AnnouncesSlugRoute;
  "/problems/$code": typeof ProblemsCodeRoute;
  "/signin/impersonation": typeof SigninImpersonationRoute;
  "/announces/": typeof AnnouncesIndexRoute;
  "/problems/": typeof ProblemsIndexRoute;
  "/signin/": typeof SigninIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/activity"
    | "/announces"
    | "/problems"
    | "/ranking"
    | "/rule"
    | "/signin"
    | "/signup"
    | "/teams"
    | "/announces/$slug"
    | "/problems/$code"
    | "/signin/impersonation"
    | "/announces/"
    | "/problems/"
    | "/signin/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/activity"
    | "/ranking"
    | "/rule"
    | "/signup"
    | "/teams"
    | "/announces/$slug"
    | "/problems/$code"
    | "/signin/impersonation"
    | "/announces"
    | "/problems"
    | "/signin";
  id:
    | "__root__"
    | "/"
    | "/activity"
    | "/announces"
    | "/problems"
    | "/ranking"
    | "/rule"
    | "/signin"
    | "/signup"
    | "/teams"
    | "/announces/$slug"
    | "/problems/$code"
    | "/signin/impersonation"
    | "/announces/"
    | "/problems/"
    | "/signin/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ActivityRoute: typeof ActivityRoute;
  AnnouncesRoute: typeof AnnouncesRouteWithChildren;
  ProblemsRoute: typeof ProblemsRouteWithChildren;
  RankingRoute: typeof RankingRoute;
  RuleRoute: typeof RuleRoute;
  SigninRoute: typeof SigninRouteWithChildren;
  SignupRoute: typeof SignupRoute;
  TeamsRoute: typeof TeamsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/teams": {
      id: "/teams";
      path: "/teams";
      fullPath: "/teams";
      preLoaderRoute: typeof TeamsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rule": {
      id: "/rule";
      path: "/rule";
      fullPath: "/rule";
      preLoaderRoute: typeof RuleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ranking": {
      id: "/ranking";
      path: "/ranking";
      fullPath: "/ranking";
      preLoaderRoute: typeof RankingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/problems": {
      id: "/problems";
      path: "/problems";
      fullPath: "/problems";
      preLoaderRoute: typeof ProblemsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/announces": {
      id: "/announces";
      path: "/announces";
      fullPath: "/announces";
      preLoaderRoute: typeof AnnouncesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/activity": {
      id: "/activity";
      path: "/activity";
      fullPath: "/activity";
      preLoaderRoute: typeof ActivityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin/": {
      id: "/signin/";
      path: "/";
      fullPath: "/signin/";
      preLoaderRoute: typeof SigninIndexRouteImport;
      parentRoute: typeof SigninRoute;
    };
    "/problems/": {
      id: "/problems/";
      path: "/";
      fullPath: "/problems/";
      preLoaderRoute: typeof ProblemsIndexRouteImport;
      parentRoute: typeof ProblemsRoute;
    };
    "/announces/": {
      id: "/announces/";
      path: "/";
      fullPath: "/announces/";
      preLoaderRoute: typeof AnnouncesIndexRouteImport;
      parentRoute: typeof AnnouncesRoute;
    };
    "/signin/impersonation": {
      id: "/signin/impersonation";
      path: "/impersonation";
      fullPath: "/signin/impersonation";
      preLoaderRoute: typeof SigninImpersonationRouteImport;
      parentRoute: typeof SigninRoute;
    };
    "/problems/$code": {
      id: "/problems/$code";
      path: "/$code";
      fullPath: "/problems/$code";
      preLoaderRoute: typeof ProblemsCodeRouteImport;
      parentRoute: typeof ProblemsRoute;
    };
    "/announces/$slug": {
      id: "/announces/$slug";
      path: "/$slug";
      fullPath: "/announces/$slug";
      preLoaderRoute: typeof AnnouncesSlugRouteImport;
      parentRoute: typeof AnnouncesRoute;
    };
  }
}

interface AnnouncesRouteChildren {
  AnnouncesSlugRoute: typeof AnnouncesSlugRoute;
  AnnouncesIndexRoute: typeof AnnouncesIndexRoute;
}

const AnnouncesRouteChildren: AnnouncesRouteChildren = {
  AnnouncesSlugRoute: AnnouncesSlugRoute,
  AnnouncesIndexRoute: AnnouncesIndexRoute,
};

const AnnouncesRouteWithChildren = AnnouncesRoute._addFileChildren(
  AnnouncesRouteChildren,
);

interface ProblemsRouteChildren {
  ProblemsCodeRoute: typeof ProblemsCodeRoute;
  ProblemsIndexRoute: typeof ProblemsIndexRoute;
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsCodeRoute: ProblemsCodeRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
};

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
);

interface SigninRouteChildren {
  SigninImpersonationRoute: typeof SigninImpersonationRoute;
  SigninIndexRoute: typeof SigninIndexRoute;
}

const SigninRouteChildren: SigninRouteChildren = {
  SigninImpersonationRoute: SigninImpersonationRoute,
  SigninIndexRoute: SigninIndexRoute,
};

const SigninRouteWithChildren =
  SigninRoute._addFileChildren(SigninRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnnouncesRoute: AnnouncesRouteWithChildren,
  ProblemsRoute: ProblemsRouteWithChildren,
  RankingRoute: RankingRoute,
  RuleRoute: RuleRoute,
  SigninRoute: SigninRouteWithChildren,
  SignupRoute: SignupRoute,
  TeamsRoute: TeamsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
