version: 3
tasks:
  generate:
    desc: 自動生成ファイルをすべて生成
    cmds:
      - task: generate-backend
      - task: generate-frontend

  generate-backend:
    internal: true
    dir: backend
    cmds:
      - go generate -x ./...

  generate-frontend:
    internal: true
    dir: frontend
    cmds:
      - pnpm install
      - pnpm run --recursive --parallel --aggregate-output generate
