linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - depguard
    - dogsled
    - godot
    - nolintlint

linters-settings:
  lll:
    line-length: 150
  varnamelen:
    ignore-names:
      - tt
  wrapcheck:
    ignoreSigs:
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/cockroachdb/errors.Newf(
      - github.com/ictsc/ictsc-outlands/backend/pkg/errors.New(

issues:
  exclude-use-default: false
