linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - depguard
    - dogsled
    - godot
    - nolintlint

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - funlen

linters-settings:
  lll:
    line-length: 150
  varnamelen:
    ignore-names:
      - tt
      - tx
  wrapcheck:
    ignoreSigs:
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/cockroachdb/errors.Newf(
      - github.com/ictsc/ictsc-outlands/backend
