linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - wsl
    - nlreturn
    - depguard
    - dogsled
    - gci
    - godot
    - nolintlint
    - gochecknoglobals
    - ireturn
    - gofumpt
    - tagliatelle

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - funlen
        - contextcheck
        - noctx

linters-settings:
  cyclop:
    max-complexity: 15
  exhaustruct:
    include:
      - github\.com/ictsc/ictsc-regalia/backend/scoreserver/domain/.+
  lll:
    line-length: 150
  revive:
    rules:
      - name: package-comments
        disabled: true
  stylecheck:
    checks:
      - all
      - -ST1000
  varnamelen:
    ignore-names:
      - tt
      - tx
      - id
      - db
      - to
      - i
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
  wrapcheck:
    ignoreSigs:
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      - github.com/cockroachdb/errors.Newf(
      - github.com/cockroachdb/errors.New(
      - github.com/cockroachdb/errors.Join(
      - github.com/ictsc/ictsc-regalia/backend
