#!/bin/sh
# vim: ft=sh :

compose_file="$(dirname "$0")/../compose.yaml"

export DB_HOST=127.0.0.1
DB_PORT="$(docker compose -f "$compose_file" port postgres 5432 | cut -d: -f2)"
export DB_PORT
export DB_USER=ictsc
export PGPASSWORD=password
export DB_NAME=ictscore

export OTEL_METRICS_EXPORTER=prometheus

if docker compose -f "$compose_file" ps | grep -q jaeger; then
	export OTEL_TRACES_EXPORTER=otlp
	OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="http://localhost:$(docker compose -f "$compose_file" port jaeger 4317 | cut -d: -f2)"
	export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
else
	export OTEL_TRACES_EXPORTER=none
fi

exec "$@"
