#!/bin/bash

set -eu

compose_file="$(dirname "$0")/../compose.yaml"
ps="$(docker compose -f "$compose_file" ps --format=json)"

export PGHOST=127.0.0.1
PGPORT="$(jq -r 'select(.Service=="postgres").Publishers[] | select(.TargetPort==5432).PublishedPort' <<< "$ps")"
export PGPORT
export PGUSER=ictsc
export PGPASSWORD=password
export PGDATABASE=ictscore
export PGSSLMODE=disable

redis_port="$(jq -r 'select(.Service=="redis").Publishers[] | select(.TargetPort==6379).PublishedPort' <<< "$ps")"
export REDIS_URL="redis://localhost:$redis_port/0"

export OTEL_METRICS_EXPORTER="${OTEL_METRICS_EXPORTER:-prometheus}"

traces_exporter=otlp
otlp_port="$(jq -r 'select(.Service=="otelcol").Publishers[] | select(.TargetPort==4317).PublishedPort' <<< "$ps")"
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-"http://localhost:$otlp_port"}"
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="${OTEL_EXPORTER_OTLP_TRACES_PROTOCOL:-grpc}"
export OTEL_TRACES_EXPORTER="${OTEL_TRACES_EXPORTER:-$traces_exporter}"

exec "$@"
