#!/bin/sh
# vim: ft=sh :

PSQLDEF="go tool github.com/sqldef/sqldef/cmd/psqldef"
if which psqldef 2>/dev/null; then
    PSQLDEF=psqldef
fi

schema_file=$(dirname "$0")/../schema.sql
view_file=$(dirname "$0")/../view.sql

$PSQLDEF --host="${PGHOST:-localhost}" --port="${PGPORT:-5432}" --user="${PGUSER:-ictsc}" --skip-view "${PGDATABASE:-ictscore}" < "$schema_file" "$@"
psql -1 < "$view_file"
