#!/bin/sh
# vim: ft=sh :

PSQLDEF="go run github.com/sqldef/sqldef/cmd/psqldef"
if which psqldef > /dev/null; then
    PSQLDEF=psqldef
fi

schema_file=$(dirname "$0")/../schema.sql

exec $PSQLDEF --host="$DB_HOST" --port="$DB_PORT" --user="$DB_USER" "$DB_NAME" < "$schema_file" "$@"
