// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file admin/v1/admin.proto (package admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAdminRequest, GetAdminResponse, GetAdminsRequest, GetAdminsResponse, GetMeRequest, GetMeResponse, PatchAdminRequest, PatchAdminResponse, PostAdminRequest, PostAdminResponse } from "./admin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service admin.v1.AdminService
 */
export const AdminService = {
  typeName: "admin.v1.AdminService",
  methods: {
    /**
     * @generated from rpc admin.v1.AdminService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: GetMeRequest,
      O: GetMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.v1.AdminService.GetAdmin
     */
    getAdmin: {
      name: "GetAdmin",
      I: GetAdminRequest,
      O: GetAdminResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.v1.AdminService.GetAdmins
     */
    getAdmins: {
      name: "GetAdmins",
      I: GetAdminsRequest,
      O: GetAdminsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.v1.AdminService.PostAdmin
     */
    postAdmin: {
      name: "PostAdmin",
      I: PostAdminRequest,
      O: PostAdminResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.v1.AdminService.PatchAdmin
     */
    patchAdmin: {
      name: "PatchAdmin",
      I: PatchAdminRequest,
      O: PatchAdminResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

