// @generated by protoc-gen-connect-query v1.2.0 with parameter "target=ts,import_extension=none"
// @generated from file admin/v1/rule.proto (package admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GetRuleRequest, GetRuleResponse, PatchRuleRequest, PatchRuleResponse } from "./rule_pb";

/**
 * @generated from rpc admin.v1.RuleService.GetRule
 */
export const getRule = {
  localName: "getRule",
  name: "GetRule",
  kind: MethodKind.Unary,
  I: GetRuleRequest,
  O: GetRuleResponse,
  service: {
    typeName: "admin.v1.RuleService"
  }
} as const;

/**
 * @generated from rpc admin.v1.RuleService.PatchRule
 */
export const patchRule = {
  localName: "patchRule",
  name: "PatchRule",
  kind: MethodKind.Unary,
  I: PatchRuleRequest,
  O: PatchRuleResponse,
  service: {
    typeName: "admin.v1.RuleService"
  }
} as const;
