// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file admin/v1/contestant.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/v1/contestant.proto.
 */
export const file_admin_v1_contestant: GenFile = /*@__PURE__*/
  fileDesc("ChlhZG1pbi92MS9jb250ZXN0YW50LnByb3RvEghhZG1pbi52MSKYAQoKQ29udGVzdGFudBIMCgRuYW1lGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIRCgl0ZWFtX2NvZGUYAyABKAMSIgoHcHJvZmlsZRgEIAEoCzIRLmFkbWluLnYxLlByb2ZpbGUSFgoOZGlzY29yZF9qb2luZWQYBSABKAgSFwoPaW52aXRhdGlvbl9jb2RlGAYgASgJIiQKB1Byb2ZpbGUSGQoRc2VsZl9pbnRyb2R1Y3Rpb24YASABKAkiKwoWTGlzdENvbnRlc3RhbnRzUmVxdWVzdBIRCgl0ZWFtX2NvZGUYASABKAMiRAoXTGlzdENvbnRlc3RhbnRzUmVzcG9uc2USKQoLY29udGVzdGFudHMYASADKAsyFC5hZG1pbi52MS5Db250ZXN0YW50MmsKEUNvbnRlc3RhbnRTZXJ2aWNlElYKD0xpc3RDb250ZXN0YW50cxIgLmFkbWluLnYxLkxpc3RDb250ZXN0YW50c1JlcXVlc3QaIS5hZG1pbi52MS5MaXN0Q29udGVzdGFudHNSZXNwb25zZUKjAQoMY29tLmFkbWluLnYxQg9Db250ZXN0YW50UHJvdG9QAVpBZ2l0aHViLmNvbS9pY3RzYy9pY3RzYy1yZWdhbGlhL2JhY2tlbmQvcGtnL3Byb3RvL2FkbWluL3YxO2FkbWludjGiAgNBWFiqAghBZG1pbi5WMcoCCEFkbWluXFYx4gIUQWRtaW5cVjFcR1BCTWV0YWRhdGHqAglBZG1pbjo6VjFiBnByb3RvMw");

/**
 * @generated from message admin.v1.Contestant
 */
export type Contestant = Message<"admin.v1.Contestant"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: int64 team_code = 3;
   */
  teamCode: bigint;

  /**
   * @generated from field: admin.v1.Profile profile = 4;
   */
  profile?: Profile;

  /**
   * @generated from field: bool discord_joined = 5;
   */
  discordJoined: boolean;

  /**
   * @generated from field: string invitation_code = 6;
   */
  invitationCode: string;
};

/**
 * Describes the message admin.v1.Contestant.
 * Use `create(ContestantSchema)` to create a new message.
 */
export const ContestantSchema: GenMessage<Contestant> = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 0);

/**
 * @generated from message admin.v1.Profile
 */
export type Profile = Message<"admin.v1.Profile"> & {
  /**
   * @generated from field: string self_introduction = 1;
   */
  selfIntroduction: string;
};

/**
 * Describes the message admin.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export const ProfileSchema: GenMessage<Profile> = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 1);

/**
 * @generated from message admin.v1.ListContestantsRequest
 */
export type ListContestantsRequest = Message<"admin.v1.ListContestantsRequest"> & {
  /**
   * @generated from field: int64 team_code = 1;
   */
  teamCode: bigint;
};

/**
 * Describes the message admin.v1.ListContestantsRequest.
 * Use `create(ListContestantsRequestSchema)` to create a new message.
 */
export const ListContestantsRequestSchema: GenMessage<ListContestantsRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 2);

/**
 * @generated from message admin.v1.ListContestantsResponse
 */
export type ListContestantsResponse = Message<"admin.v1.ListContestantsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Contestant contestants = 1;
   */
  contestants: Contestant[];
};

/**
 * Describes the message admin.v1.ListContestantsResponse.
 * Use `create(ListContestantsResponseSchema)` to create a new message.
 */
export const ListContestantsResponseSchema: GenMessage<ListContestantsResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 3);

/**
 * @generated from service admin.v1.ContestantService
 */
export const ContestantService: GenService<{
  /**
   * @generated from rpc admin.v1.ContestantService.ListContestants
   */
  listContestants: {
    methodKind: "unary";
    input: typeof ListContestantsRequestSchema;
    output: typeof ListContestantsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_v1_contestant, 0);

