// @generated by protoc-gen-es v2.9.0 with parameter "target=js+dts"
// @generated from file admin/v1/contestant.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_admin_v1_team } from "./team_pb";

/**
 * Describes the file admin/v1/contestant.proto.
 */
export const file_admin_v1_contestant = /*@__PURE__*/
  fileDesc("ChlhZG1pbi92MS9jb250ZXN0YW50LnByb3RvEghhZG1pbi52MSKGAQoKQ29udGVzdGFudBIMCgRuYW1lGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIcCgR0ZWFtGAMgASgLMg4uYWRtaW4udjEuVGVhbRIiCgdwcm9maWxlGAQgASgLMhEuYWRtaW4udjEuUHJvZmlsZRISCgpkaXNjb3JkX2lkGAUgASgJIiQKB1Byb2ZpbGUSGQoRc2VsZl9pbnRyb2R1Y3Rpb24YASABKAkiKwoWTGlzdENvbnRlc3RhbnRzUmVxdWVzdBIRCgl0ZWFtX2NvZGUYASABKAMiRAoXTGlzdENvbnRlc3RhbnRzUmVzcG9uc2USKQoLY29udGVzdGFudHMYASADKAsyFC5hZG1pbi52MS5Db250ZXN0YW50MmsKEUNvbnRlc3RhbnRTZXJ2aWNlElYKD0xpc3RDb250ZXN0YW50cxIgLmFkbWluLnYxLkxpc3RDb250ZXN0YW50c1JlcXVlc3QaIS5hZG1pbi52MS5MaXN0Q29udGVzdGFudHNSZXNwb25zZUKjAQoMY29tLmFkbWluLnYxQg9Db250ZXN0YW50UHJvdG9QAVpBZ2l0aHViLmNvbS9pY3RzYy9pY3RzYy1yZWdhbGlhL2JhY2tlbmQvcGtnL3Byb3RvL2FkbWluL3YxO2FkbWludjGiAgNBWFiqAghBZG1pbi5WMcoCCEFkbWluXFYx4gIUQWRtaW5cVjFcR1BCTWV0YWRhdGHqAglBZG1pbjo6VjFiBnByb3RvMw", [file_admin_v1_team]);

/**
 * Describes the message admin.v1.Contestant.
 * Use `create(ContestantSchema)` to create a new message.
 */
export const ContestantSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 0);

/**
 * Describes the message admin.v1.Profile.
 * Use `create(ProfileSchema)` to create a new message.
 */
export const ProfileSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 1);

/**
 * Describes the message admin.v1.ListContestantsRequest.
 * Use `create(ListContestantsRequestSchema)` to create a new message.
 */
export const ListContestantsRequestSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 2);

/**
 * Describes the message admin.v1.ListContestantsResponse.
 * Use `create(ListContestantsResponseSchema)` to create a new message.
 */
export const ListContestantsResponseSchema = /*@__PURE__*/
  messageDesc(file_admin_v1_contestant, 3);

/**
 * @generated from service admin.v1.ContestantService
 */
export const ContestantService = /*@__PURE__*/
  serviceDesc(file_admin_v1_contestant, 0);

