// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file admin/v1/notice.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/v1/notice.proto.
 */
export const file_admin_v1_notice: GenFile = /*@__PURE__*/
  fileDesc("ChVhZG1pbi92MS9ub3RpY2UucHJvdG8SCGFkbWluLnYxIjcKBk5vdGljZRIMCgRwYXRoGAEgASgJEg0KBXRpdGxlGAIgASgJEhAKCG1hcmtkb3duGAMgASgJIhQKEkxpc3ROb3RpY2VzUmVxdWVzdCI4ChNMaXN0Tm90aWNlc1Jlc3BvbnNlEiEKB25vdGljZXMYASADKAsyEC5hZG1pbi52MS5Ob3RpY2UiIgoSU3luY05vdGljZXNSZXF1ZXN0EgwKBHBhdGgYASABKAkiNwoTU3luY05vdGljZXNSZXNwb25zZRIgCgZub3RpY2UYASABKAsyEC5hZG1pbi52MS5Ob3RpY2UypwEKDU5vdGljZVNlcnZpY2USSgoLTGlzdE5vdGljZXMSHC5hZG1pbi52MS5MaXN0Tm90aWNlc1JlcXVlc3QaHS5hZG1pbi52MS5MaXN0Tm90aWNlc1Jlc3BvbnNlEkoKC1N5bmNOb3RpY2VzEhwuYWRtaW4udjEuU3luY05vdGljZXNSZXF1ZXN0Gh0uYWRtaW4udjEuU3luY05vdGljZXNSZXNwb25zZUKfAQoMY29tLmFkbWluLnYxQgtOb3RpY2VQcm90b1ABWkFnaXRodWIuY29tL2ljdHNjL2ljdHNjLXJlZ2FsaWEvYmFja2VuZC9wa2cvcHJvdG8vYWRtaW4vdjE7YWRtaW52MaICA0FYWKoCCEFkbWluLlYxygIIQWRtaW5cVjHiAhRBZG1pblxWMVxHUEJNZXRhZGF0YeoCCUFkbWluOjpWMWIGcHJvdG8z");

/**
 * @generated from message admin.v1.Notice
 */
export type Notice = Message<"admin.v1.Notice"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string markdown = 3;
   */
  markdown: string;
};

/**
 * Describes the message admin.v1.Notice.
 * Use `create(NoticeSchema)` to create a new message.
 */
export const NoticeSchema: GenMessage<Notice> = /*@__PURE__*/
  messageDesc(file_admin_v1_notice, 0);

/**
 * @generated from message admin.v1.ListNoticesRequest
 */
export type ListNoticesRequest = Message<"admin.v1.ListNoticesRequest"> & {
};

/**
 * Describes the message admin.v1.ListNoticesRequest.
 * Use `create(ListNoticesRequestSchema)` to create a new message.
 */
export const ListNoticesRequestSchema: GenMessage<ListNoticesRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_notice, 1);

/**
 * @generated from message admin.v1.ListNoticesResponse
 */
export type ListNoticesResponse = Message<"admin.v1.ListNoticesResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Notice notices = 1;
   */
  notices: Notice[];
};

/**
 * Describes the message admin.v1.ListNoticesResponse.
 * Use `create(ListNoticesResponseSchema)` to create a new message.
 */
export const ListNoticesResponseSchema: GenMessage<ListNoticesResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_notice, 2);

/**
 * @generated from message admin.v1.SyncNoticesRequest
 */
export type SyncNoticesRequest = Message<"admin.v1.SyncNoticesRequest"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message admin.v1.SyncNoticesRequest.
 * Use `create(SyncNoticesRequestSchema)` to create a new message.
 */
export const SyncNoticesRequestSchema: GenMessage<SyncNoticesRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_notice, 3);

/**
 * @generated from message admin.v1.SyncNoticesResponse
 */
export type SyncNoticesResponse = Message<"admin.v1.SyncNoticesResponse"> & {
  /**
   * @generated from field: admin.v1.Notice notice = 1;
   */
  notice?: Notice;
};

/**
 * Describes the message admin.v1.SyncNoticesResponse.
 * Use `create(SyncNoticesResponseSchema)` to create a new message.
 */
export const SyncNoticesResponseSchema: GenMessage<SyncNoticesResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_notice, 4);

/**
 * @generated from service admin.v1.NoticeService
 */
export const NoticeService: GenService<{
  /**
   * @generated from rpc admin.v1.NoticeService.ListNotices
   */
  listNotices: {
    methodKind: "unary";
    input: typeof ListNoticesRequestSchema;
    output: typeof ListNoticesResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.NoticeService.SyncNotices
   */
  syncNotices: {
    methodKind: "unary";
    input: typeof SyncNoticesRequestSchema;
    output: typeof SyncNoticesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_v1_notice, 0);

