// @generated by protoc-gen-es v2.9.0 with parameter "target=js+dts"
// @generated from file admin/v1/schedule.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file admin/v1/schedule.proto.
 */
export declare const file_admin_v1_schedule: GenFile;

/**
 * @generated from message admin.v1.Schedule
 */
export declare type Schedule = Message<"admin.v1.Schedule"> & {
  /**
   * @generated from field: admin.v1.Phase phase = 1;
   */
  phase: Phase;

  /**
   * @generated from field: google.protobuf.Timestamp start_at = 2;
   */
  startAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_at = 3;
   */
  endAt?: Timestamp;
};

/**
 * Describes the message admin.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export declare const ScheduleSchema: GenMessage<Schedule>;

/**
 * @generated from message admin.v1.GetScheduleRequest
 */
export declare type GetScheduleRequest = Message<"admin.v1.GetScheduleRequest"> & {
};

/**
 * Describes the message admin.v1.GetScheduleRequest.
 * Use `create(GetScheduleRequestSchema)` to create a new message.
 */
export declare const GetScheduleRequestSchema: GenMessage<GetScheduleRequest>;

/**
 * @generated from message admin.v1.GetScheduleResponse
 */
export declare type GetScheduleResponse = Message<"admin.v1.GetScheduleResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Schedule schedule = 1;
   */
  schedule: Schedule[];
};

/**
 * Describes the message admin.v1.GetScheduleResponse.
 * Use `create(GetScheduleResponseSchema)` to create a new message.
 */
export declare const GetScheduleResponseSchema: GenMessage<GetScheduleResponse>;

/**
 * @generated from message admin.v1.UpdateScheduleRequest
 */
export declare type UpdateScheduleRequest = Message<"admin.v1.UpdateScheduleRequest"> & {
  /**
   * @generated from field: repeated admin.v1.Schedule schedule = 1;
   */
  schedule: Schedule[];
};

/**
 * Describes the message admin.v1.UpdateScheduleRequest.
 * Use `create(UpdateScheduleRequestSchema)` to create a new message.
 */
export declare const UpdateScheduleRequestSchema: GenMessage<UpdateScheduleRequest>;

/**
 * @generated from message admin.v1.UpdateScheduleResponse
 */
export declare type UpdateScheduleResponse = Message<"admin.v1.UpdateScheduleResponse"> & {
};

/**
 * Describes the message admin.v1.UpdateScheduleResponse.
 * Use `create(UpdateScheduleResponseSchema)` to create a new message.
 */
export declare const UpdateScheduleResponseSchema: GenMessage<UpdateScheduleResponse>;

/**
 * @generated from enum admin.v1.Phase
 */
export enum Phase {
  /**
   * @generated from enum value: PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PHASE_OUT_OF_CONTEST = 1;
   */
  OUT_OF_CONTEST = 1,

  /**
   * @generated from enum value: PHASE_IN_CONTEST = 2;
   */
  IN_CONTEST = 2,

  /**
   * @generated from enum value: PHASE_BREAK = 3;
   */
  BREAK = 3,

  /**
   * @generated from enum value: PHASE_AFTER_CONTEST = 4;
   */
  AFTER_CONTEST = 4,
}

/**
 * Describes the enum admin.v1.Phase.
 */
export declare const PhaseSchema: GenEnum<Phase>;

/**
 * @generated from service admin.v1.ScheduleService
 */
export declare const ScheduleService: GenService<{
  /**
   * @generated from rpc admin.v1.ScheduleService.GetSchedule
   */
  getSchedule: {
    methodKind: "unary";
    input: typeof GetScheduleRequestSchema;
    output: typeof GetScheduleResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.ScheduleService.UpdateSchedule
   */
  updateSchedule: {
    methodKind: "unary";
    input: typeof UpdateScheduleRequestSchema;
    output: typeof UpdateScheduleResponseSchema;
  },
}>;

