// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file admin/v1/team.proto (package admin.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { FieldMask } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file admin/v1/team.proto.
 */
export const file_admin_v1_team: GenFile = /*@__PURE__*/
  fileDesc("ChNhZG1pbi92MS90ZWFtLnByb3RvEghhZG1pbi52MSJrCgRUZWFtEhcKBGNvZGUYAiABKANCCbpIBiIEEGQgARIVCgRuYW1lGAMgASgJQge6SARyAhABEh0KDG9yZ2FuaXphdGlvbhgEIAEoCUIHukgEcgIQARIUCgxtZW1iZXJfbGltaXQYBSABKA0iEgoQTGlzdFRlYW1zUmVxdWVzdCI6ChFMaXN0VGVhbXNSZXNwb25zZRIlCgV0ZWFtcxgBIAMoCzIOLmFkbWluLnYxLlRlYW1CBrpIA8gBASIpCg5HZXRUZWFtUmVxdWVzdBIXCgRjb2RlGAEgASgDQgm6SAYiBBBkIAEiNwoPR2V0VGVhbVJlc3BvbnNlEiQKBHRlYW0YASABKAsyDi5hZG1pbi52MS5UZWFtQga6SAPIAQEiOQoRQ3JlYXRlVGVhbVJlcXVlc3QSJAoEdGVhbRgBIAEoCzIOLmFkbWluLnYxLlRlYW1CBrpIA8gBASI6ChJDcmVhdGVUZWFtUmVzcG9uc2USJAoEdGVhbRgBIAEoCzIOLmFkbWluLnYxLlRlYW1CBrpIA8gBASJqChFVcGRhdGVUZWFtUmVxdWVzdBIkCgR0ZWFtGAEgASgLMg4uYWRtaW4udjEuVGVhbUIGukgDyAEBEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzayI6ChJVcGRhdGVUZWFtUmVzcG9uc2USJAoEdGVhbRgBIAEoCzIOLmFkbWluLnYxLlRlYW1CBrpIA8gBASIsChFEZWxldGVUZWFtUmVxdWVzdBIXCgRjb2RlGAEgASgDQgm6SAYiBBBkIAEiFAoSRGVsZXRlVGVhbVJlc3BvbnNlMu4CCgtUZWFtU2VydmljZRJECglMaXN0VGVhbXMSGi5hZG1pbi52MS5MaXN0VGVhbXNSZXF1ZXN0GhsuYWRtaW4udjEuTGlzdFRlYW1zUmVzcG9uc2USPgoHR2V0VGVhbRIYLmFkbWluLnYxLkdldFRlYW1SZXF1ZXN0GhkuYWRtaW4udjEuR2V0VGVhbVJlc3BvbnNlEkcKCkNyZWF0ZVRlYW0SGy5hZG1pbi52MS5DcmVhdGVUZWFtUmVxdWVzdBocLmFkbWluLnYxLkNyZWF0ZVRlYW1SZXNwb25zZRJHCgpVcGRhdGVUZWFtEhsuYWRtaW4udjEuVXBkYXRlVGVhbVJlcXVlc3QaHC5hZG1pbi52MS5VcGRhdGVUZWFtUmVzcG9uc2USRwoKRGVsZXRlVGVhbRIbLmFkbWluLnYxLkRlbGV0ZVRlYW1SZXF1ZXN0GhwuYWRtaW4udjEuRGVsZXRlVGVhbVJlc3BvbnNlQp0BCgxjb20uYWRtaW4udjFCCVRlYW1Qcm90b1ABWkFnaXRodWIuY29tL2ljdHNjL2ljdHNjLXJlZ2FsaWEvYmFja2VuZC9wa2cvcHJvdG8vYWRtaW4vdjE7YWRtaW52MaICA0FYWKoCCEFkbWluLlYxygIIQWRtaW5cVjHiAhRBZG1pblxWMVxHUEJNZXRhZGF0YeoCCUFkbWluOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_field_mask]);

/**
 * @generated from message admin.v1.Team
 */
export type Team = Message<"admin.v1.Team"> & {
  /**
   * @generated from field: int64 code = 2;
   */
  code: bigint;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string organization = 4;
   */
  organization: string;

  /**
   * @generated from field: uint32 member_limit = 5;
   */
  memberLimit: number;
};

/**
 * Describes the message admin.v1.Team.
 * Use `create(TeamSchema)` to create a new message.
 */
export const TeamSchema: GenMessage<Team> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 0);

/**
 * @generated from message admin.v1.ListTeamsRequest
 */
export type ListTeamsRequest = Message<"admin.v1.ListTeamsRequest"> & {
};

/**
 * Describes the message admin.v1.ListTeamsRequest.
 * Use `create(ListTeamsRequestSchema)` to create a new message.
 */
export const ListTeamsRequestSchema: GenMessage<ListTeamsRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 1);

/**
 * @generated from message admin.v1.ListTeamsResponse
 */
export type ListTeamsResponse = Message<"admin.v1.ListTeamsResponse"> & {
  /**
   * @generated from field: repeated admin.v1.Team teams = 1;
   */
  teams: Team[];
};

/**
 * Describes the message admin.v1.ListTeamsResponse.
 * Use `create(ListTeamsResponseSchema)` to create a new message.
 */
export const ListTeamsResponseSchema: GenMessage<ListTeamsResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 2);

/**
 * @generated from message admin.v1.GetTeamRequest
 */
export type GetTeamRequest = Message<"admin.v1.GetTeamRequest"> & {
  /**
   * @generated from field: int64 code = 1;
   */
  code: bigint;
};

/**
 * Describes the message admin.v1.GetTeamRequest.
 * Use `create(GetTeamRequestSchema)` to create a new message.
 */
export const GetTeamRequestSchema: GenMessage<GetTeamRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 3);

/**
 * @generated from message admin.v1.GetTeamResponse
 */
export type GetTeamResponse = Message<"admin.v1.GetTeamResponse"> & {
  /**
   * @generated from field: admin.v1.Team team = 1;
   */
  team?: Team;
};

/**
 * Describes the message admin.v1.GetTeamResponse.
 * Use `create(GetTeamResponseSchema)` to create a new message.
 */
export const GetTeamResponseSchema: GenMessage<GetTeamResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 4);

/**
 * @generated from message admin.v1.CreateTeamRequest
 */
export type CreateTeamRequest = Message<"admin.v1.CreateTeamRequest"> & {
  /**
   * @generated from field: admin.v1.Team team = 1;
   */
  team?: Team;
};

/**
 * Describes the message admin.v1.CreateTeamRequest.
 * Use `create(CreateTeamRequestSchema)` to create a new message.
 */
export const CreateTeamRequestSchema: GenMessage<CreateTeamRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 5);

/**
 * @generated from message admin.v1.CreateTeamResponse
 */
export type CreateTeamResponse = Message<"admin.v1.CreateTeamResponse"> & {
  /**
   * @generated from field: admin.v1.Team team = 1;
   */
  team?: Team;
};

/**
 * Describes the message admin.v1.CreateTeamResponse.
 * Use `create(CreateTeamResponseSchema)` to create a new message.
 */
export const CreateTeamResponseSchema: GenMessage<CreateTeamResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 6);

/**
 * @generated from message admin.v1.UpdateTeamRequest
 */
export type UpdateTeamRequest = Message<"admin.v1.UpdateTeamRequest"> & {
  /**
   * @generated from field: admin.v1.Team team = 1;
   */
  team?: Team;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message admin.v1.UpdateTeamRequest.
 * Use `create(UpdateTeamRequestSchema)` to create a new message.
 */
export const UpdateTeamRequestSchema: GenMessage<UpdateTeamRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 7);

/**
 * @generated from message admin.v1.UpdateTeamResponse
 */
export type UpdateTeamResponse = Message<"admin.v1.UpdateTeamResponse"> & {
  /**
   * @generated from field: admin.v1.Team team = 1;
   */
  team?: Team;
};

/**
 * Describes the message admin.v1.UpdateTeamResponse.
 * Use `create(UpdateTeamResponseSchema)` to create a new message.
 */
export const UpdateTeamResponseSchema: GenMessage<UpdateTeamResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 8);

/**
 * @generated from message admin.v1.DeleteTeamRequest
 */
export type DeleteTeamRequest = Message<"admin.v1.DeleteTeamRequest"> & {
  /**
   * @generated from field: int64 code = 1;
   */
  code: bigint;
};

/**
 * Describes the message admin.v1.DeleteTeamRequest.
 * Use `create(DeleteTeamRequestSchema)` to create a new message.
 */
export const DeleteTeamRequestSchema: GenMessage<DeleteTeamRequest> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 9);

/**
 * @generated from message admin.v1.DeleteTeamResponse
 */
export type DeleteTeamResponse = Message<"admin.v1.DeleteTeamResponse"> & {
};

/**
 * Describes the message admin.v1.DeleteTeamResponse.
 * Use `create(DeleteTeamResponseSchema)` to create a new message.
 */
export const DeleteTeamResponseSchema: GenMessage<DeleteTeamResponse> = /*@__PURE__*/
  messageDesc(file_admin_v1_team, 10);

/**
 * @generated from service admin.v1.TeamService
 */
export const TeamService: GenService<{
  /**
   * @generated from rpc admin.v1.TeamService.ListTeams
   */
  listTeams: {
    methodKind: "unary";
    input: typeof ListTeamsRequestSchema;
    output: typeof ListTeamsResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TeamService.GetTeam
   */
  getTeam: {
    methodKind: "unary";
    input: typeof GetTeamRequestSchema;
    output: typeof GetTeamResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TeamService.CreateTeam
   */
  createTeam: {
    methodKind: "unary";
    input: typeof CreateTeamRequestSchema;
    output: typeof CreateTeamResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TeamService.UpdateTeam
   */
  updateTeam: {
    methodKind: "unary";
    input: typeof UpdateTeamRequestSchema;
    output: typeof UpdateTeamResponseSchema;
  },
  /**
   * @generated from rpc admin.v1.TeamService.DeleteTeam
   */
  deleteTeam: {
    methodKind: "unary";
    input: typeof DeleteTeamRequestSchema;
    output: typeof DeleteTeamResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_admin_v1_team, 0);

