// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: admin/v1/actor.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_admin_v1_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_admin_v1_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_admin_v1_actor_proto protoreflect.FileDescriptor

const file_admin_v1_actor_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/actor.proto\x12\badmin.v1\"\x1b\n" +
	"\x05Admin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameBCZAgithub.com/ictsc/ictsc-regalia/backend/pkg/proto/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_actor_proto_rawDescOnce sync.Once
	file_admin_v1_actor_proto_rawDescData []byte
)

func file_admin_v1_actor_proto_rawDescGZIP() []byte {
	file_admin_v1_actor_proto_rawDescOnce.Do(func() {
		file_admin_v1_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_actor_proto_rawDesc), len(file_admin_v1_actor_proto_rawDesc)))
	})
	return file_admin_v1_actor_proto_rawDescData
}

var file_admin_v1_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_admin_v1_actor_proto_goTypes = []any{
	(*Admin)(nil), // 0: admin.v1.Admin
}
var file_admin_v1_actor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_actor_proto_init() }
func file_admin_v1_actor_proto_init() {
	if File_admin_v1_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_actor_proto_rawDesc), len(file_admin_v1_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_actor_proto_goTypes,
		DependencyIndexes: file_admin_v1_actor_proto_depIdxs,
		MessageInfos:      file_admin_v1_actor_proto_msgTypes,
	}.Build()
	File_admin_v1_actor_proto = out.File
	file_admin_v1_actor_proto_goTypes = nil
	file_admin_v1_actor_proto_depIdxs = nil
}
