// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: admin/v1/problem.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ictsc/ictsc-regalia/backend/pkg/proto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProblemServiceName is the fully-qualified name of the ProblemService service.
	ProblemServiceName = "admin.v1.ProblemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProblemServiceListProblemsProcedure is the fully-qualified name of the ProblemService's
	// ListProblems RPC.
	ProblemServiceListProblemsProcedure = "/admin.v1.ProblemService/ListProblems"
	// ProblemServiceGetProblemProcedure is the fully-qualified name of the ProblemService's GetProblem
	// RPC.
	ProblemServiceGetProblemProcedure = "/admin.v1.ProblemService/GetProblem"
	// ProblemServiceCreateProblemProcedure is the fully-qualified name of the ProblemService's
	// CreateProblem RPC.
	ProblemServiceCreateProblemProcedure = "/admin.v1.ProblemService/CreateProblem"
	// ProblemServiceUpdateProblemProcedure is the fully-qualified name of the ProblemService's
	// UpdateProblem RPC.
	ProblemServiceUpdateProblemProcedure = "/admin.v1.ProblemService/UpdateProblem"
	// ProblemServiceDeleteProblemProcedure is the fully-qualified name of the ProblemService's
	// DeleteProblem RPC.
	ProblemServiceDeleteProblemProcedure = "/admin.v1.ProblemService/DeleteProblem"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	problemServiceServiceDescriptor             = v1.File_admin_v1_problem_proto.Services().ByName("ProblemService")
	problemServiceListProblemsMethodDescriptor  = problemServiceServiceDescriptor.Methods().ByName("ListProblems")
	problemServiceGetProblemMethodDescriptor    = problemServiceServiceDescriptor.Methods().ByName("GetProblem")
	problemServiceCreateProblemMethodDescriptor = problemServiceServiceDescriptor.Methods().ByName("CreateProblem")
	problemServiceUpdateProblemMethodDescriptor = problemServiceServiceDescriptor.Methods().ByName("UpdateProblem")
	problemServiceDeleteProblemMethodDescriptor = problemServiceServiceDescriptor.Methods().ByName("DeleteProblem")
)

// ProblemServiceClient is a client for the admin.v1.ProblemService service.
type ProblemServiceClient interface {
	ListProblems(context.Context, *connect.Request[v1.ListProblemsRequest]) (*connect.Response[v1.ListProblemsResponse], error)
	GetProblem(context.Context, *connect.Request[v1.GetProblemRequest]) (*connect.Response[v1.GetProblemResponse], error)
	CreateProblem(context.Context, *connect.Request[v1.CreateProblemRequest]) (*connect.Response[v1.CreateProblemResponse], error)
	UpdateProblem(context.Context, *connect.Request[v1.UpdateProblemRequest]) (*connect.Response[v1.UpdateProblemResponse], error)
	DeleteProblem(context.Context, *connect.Request[v1.DeleteProblemRequest]) (*connect.Response[v1.DeleteProblemResponse], error)
}

// NewProblemServiceClient constructs a client for the admin.v1.ProblemService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProblemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProblemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &problemServiceClient{
		listProblems: connect.NewClient[v1.ListProblemsRequest, v1.ListProblemsResponse](
			httpClient,
			baseURL+ProblemServiceListProblemsProcedure,
			connect.WithSchema(problemServiceListProblemsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getProblem: connect.NewClient[v1.GetProblemRequest, v1.GetProblemResponse](
			httpClient,
			baseURL+ProblemServiceGetProblemProcedure,
			connect.WithSchema(problemServiceGetProblemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createProblem: connect.NewClient[v1.CreateProblemRequest, v1.CreateProblemResponse](
			httpClient,
			baseURL+ProblemServiceCreateProblemProcedure,
			connect.WithSchema(problemServiceCreateProblemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateProblem: connect.NewClient[v1.UpdateProblemRequest, v1.UpdateProblemResponse](
			httpClient,
			baseURL+ProblemServiceUpdateProblemProcedure,
			connect.WithSchema(problemServiceUpdateProblemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteProblem: connect.NewClient[v1.DeleteProblemRequest, v1.DeleteProblemResponse](
			httpClient,
			baseURL+ProblemServiceDeleteProblemProcedure,
			connect.WithSchema(problemServiceDeleteProblemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// problemServiceClient implements ProblemServiceClient.
type problemServiceClient struct {
	listProblems  *connect.Client[v1.ListProblemsRequest, v1.ListProblemsResponse]
	getProblem    *connect.Client[v1.GetProblemRequest, v1.GetProblemResponse]
	createProblem *connect.Client[v1.CreateProblemRequest, v1.CreateProblemResponse]
	updateProblem *connect.Client[v1.UpdateProblemRequest, v1.UpdateProblemResponse]
	deleteProblem *connect.Client[v1.DeleteProblemRequest, v1.DeleteProblemResponse]
}

// ListProblems calls admin.v1.ProblemService.ListProblems.
func (c *problemServiceClient) ListProblems(ctx context.Context, req *connect.Request[v1.ListProblemsRequest]) (*connect.Response[v1.ListProblemsResponse], error) {
	return c.listProblems.CallUnary(ctx, req)
}

// GetProblem calls admin.v1.ProblemService.GetProblem.
func (c *problemServiceClient) GetProblem(ctx context.Context, req *connect.Request[v1.GetProblemRequest]) (*connect.Response[v1.GetProblemResponse], error) {
	return c.getProblem.CallUnary(ctx, req)
}

// CreateProblem calls admin.v1.ProblemService.CreateProblem.
func (c *problemServiceClient) CreateProblem(ctx context.Context, req *connect.Request[v1.CreateProblemRequest]) (*connect.Response[v1.CreateProblemResponse], error) {
	return c.createProblem.CallUnary(ctx, req)
}

// UpdateProblem calls admin.v1.ProblemService.UpdateProblem.
func (c *problemServiceClient) UpdateProblem(ctx context.Context, req *connect.Request[v1.UpdateProblemRequest]) (*connect.Response[v1.UpdateProblemResponse], error) {
	return c.updateProblem.CallUnary(ctx, req)
}

// DeleteProblem calls admin.v1.ProblemService.DeleteProblem.
func (c *problemServiceClient) DeleteProblem(ctx context.Context, req *connect.Request[v1.DeleteProblemRequest]) (*connect.Response[v1.DeleteProblemResponse], error) {
	return c.deleteProblem.CallUnary(ctx, req)
}

// ProblemServiceHandler is an implementation of the admin.v1.ProblemService service.
type ProblemServiceHandler interface {
	ListProblems(context.Context, *connect.Request[v1.ListProblemsRequest]) (*connect.Response[v1.ListProblemsResponse], error)
	GetProblem(context.Context, *connect.Request[v1.GetProblemRequest]) (*connect.Response[v1.GetProblemResponse], error)
	CreateProblem(context.Context, *connect.Request[v1.CreateProblemRequest]) (*connect.Response[v1.CreateProblemResponse], error)
	UpdateProblem(context.Context, *connect.Request[v1.UpdateProblemRequest]) (*connect.Response[v1.UpdateProblemResponse], error)
	DeleteProblem(context.Context, *connect.Request[v1.DeleteProblemRequest]) (*connect.Response[v1.DeleteProblemResponse], error)
}

// NewProblemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProblemServiceHandler(svc ProblemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	problemServiceListProblemsHandler := connect.NewUnaryHandler(
		ProblemServiceListProblemsProcedure,
		svc.ListProblems,
		connect.WithSchema(problemServiceListProblemsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	problemServiceGetProblemHandler := connect.NewUnaryHandler(
		ProblemServiceGetProblemProcedure,
		svc.GetProblem,
		connect.WithSchema(problemServiceGetProblemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	problemServiceCreateProblemHandler := connect.NewUnaryHandler(
		ProblemServiceCreateProblemProcedure,
		svc.CreateProblem,
		connect.WithSchema(problemServiceCreateProblemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	problemServiceUpdateProblemHandler := connect.NewUnaryHandler(
		ProblemServiceUpdateProblemProcedure,
		svc.UpdateProblem,
		connect.WithSchema(problemServiceUpdateProblemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	problemServiceDeleteProblemHandler := connect.NewUnaryHandler(
		ProblemServiceDeleteProblemProcedure,
		svc.DeleteProblem,
		connect.WithSchema(problemServiceDeleteProblemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/admin.v1.ProblemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProblemServiceListProblemsProcedure:
			problemServiceListProblemsHandler.ServeHTTP(w, r)
		case ProblemServiceGetProblemProcedure:
			problemServiceGetProblemHandler.ServeHTTP(w, r)
		case ProblemServiceCreateProblemProcedure:
			problemServiceCreateProblemHandler.ServeHTTP(w, r)
		case ProblemServiceUpdateProblemProcedure:
			problemServiceUpdateProblemHandler.ServeHTTP(w, r)
		case ProblemServiceDeleteProblemProcedure:
			problemServiceDeleteProblemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProblemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProblemServiceHandler struct{}

func (UnimplementedProblemServiceHandler) ListProblems(context.Context, *connect.Request[v1.ListProblemsRequest]) (*connect.Response[v1.ListProblemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.ProblemService.ListProblems is not implemented"))
}

func (UnimplementedProblemServiceHandler) GetProblem(context.Context, *connect.Request[v1.GetProblemRequest]) (*connect.Response[v1.GetProblemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.ProblemService.GetProblem is not implemented"))
}

func (UnimplementedProblemServiceHandler) CreateProblem(context.Context, *connect.Request[v1.CreateProblemRequest]) (*connect.Response[v1.CreateProblemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.ProblemService.CreateProblem is not implemented"))
}

func (UnimplementedProblemServiceHandler) UpdateProblem(context.Context, *connect.Request[v1.UpdateProblemRequest]) (*connect.Response[v1.UpdateProblemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.ProblemService.UpdateProblem is not implemented"))
}

func (UnimplementedProblemServiceHandler) DeleteProblem(context.Context, *connect.Request[v1.DeleteProblemRequest]) (*connect.Response[v1.DeleteProblemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admin.v1.ProblemService.DeleteProblem is not implemented"))
}
