// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file contestant/v1/announcement.proto (package contestant.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAnnouncementsRequest, GetAnnouncementsResponse } from "./announcement_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service contestant.v1.AnnouncementService
 */
export const AnnouncementService = {
  typeName: "contestant.v1.AnnouncementService",
  methods: {
    /**
     * @generated from rpc contestant.v1.AnnouncementService.GetAnnouncements
     */
    getAnnouncements: {
      name: "GetAnnouncements",
      I: GetAnnouncementsRequest,
      O: GetAnnouncementsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

