// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file contestant/v1/problem.proto (package contestant.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetProblemRequest, GetProblemResponse, GetProblemsRequest, GetProblemsResponse } from "./problem_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service contestant.v1.ProblemService
 */
export const ProblemService = {
  typeName: "contestant.v1.ProblemService",
  methods: {
    /**
     * @generated from rpc contestant.v1.ProblemService.GetProblem
     */
    getProblem: {
      name: "GetProblem",
      I: GetProblemRequest,
      O: GetProblemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc contestant.v1.ProblemService.GetProblems
     */
    getProblems: {
      name: "GetProblems",
      I: GetProblemsRequest,
      O: GetProblemsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

