// @generated by protoc-gen-es v2.9.0 with parameter "target=js+dts"
// @generated from file contestant/v1/answer.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_contestant_v1_problem } from "./problem_pb";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file contestant/v1/answer.proto.
 */
export const file_contestant_v1_answer = /*@__PURE__*/
  fileDesc("Chpjb250ZXN0YW50L3YxL2Fuc3dlci5wcm90bxINY29udGVzdGFudC52MSKjAQoGQW5zd2VyEgoKAmlkGAEgASgNEicKBGJvZHkYAiABKAsyGS5jb250ZXN0YW50LnYxLkFuc3dlckJvZHkSMAoMc3VibWl0dGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIoCgVzY29yZRgEIAEoCzIULmNvbnRlc3RhbnQudjEuU2NvcmVIAIgBAUIICgZfc2NvcmUidwoKQW5zd2VyQm9keRIoCgR0eXBlGAEgASgOMhouY29udGVzdGFudC52MS5Qcm9ibGVtVHlwZRI3CgtkZXNjcmlwdGl2ZRgCIAEoCzIgLmNvbnRlc3RhbnQudjEuRGVzY3JpcHRpdmVBbnN3ZXJIAEIGCgRib2R5IiEKEURlc2NyaXB0aXZlQW5zd2VyEgwKBGJvZHkYASABKAkiKgoSTGlzdEFuc3dlcnNSZXF1ZXN0EhQKDHByb2JsZW1fY29kZRgBIAEoCSLDAQoTTGlzdEFuc3dlcnNSZXNwb25zZRImCgdhbnN3ZXJzGAEgAygLMhUuY29udGVzdGFudC52MS5BbnN3ZXISMgoPc3VibWl0X2ludGVydmFsGAIgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEjoKEWxhc3Rfc3VibWl0dGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBQhQKEl9sYXN0X3N1Ym1pdHRlZF9hdCI5ChNTdWJtaXRBbnN3ZXJSZXF1ZXN0EhQKDHByb2JsZW1fY29kZRgBIAEoCRIMCgRib2R5GAIgASgJIj0KFFN1Ym1pdEFuc3dlclJlc3BvbnNlEiUKBmFuc3dlchgBIAEoCzIVLmNvbnRlc3RhbnQudjEuQW5zd2VyIjQKEEdldEFuc3dlclJlcXVlc3QSFAoMcHJvYmxlbV9jb2RlGAEgASgJEgoKAmlkGAIgASgNIjoKEUdldEFuc3dlclJlc3BvbnNlEiUKBmFuc3dlchgBIAEoCzIVLmNvbnRlc3RhbnQudjEuQW5zd2VyMo4CCg1BbnN3ZXJTZXJ2aWNlElQKC0xpc3RBbnN3ZXJzEiEuY29udGVzdGFudC52MS5MaXN0QW5zd2Vyc1JlcXVlc3QaIi5jb250ZXN0YW50LnYxLkxpc3RBbnN3ZXJzUmVzcG9uc2USVwoMU3VibWl0QW5zd2VyEiIuY29udGVzdGFudC52MS5TdWJtaXRBbnN3ZXJSZXF1ZXN0GiMuY29udGVzdGFudC52MS5TdWJtaXRBbnN3ZXJSZXNwb25zZRJOCglHZXRBbnN3ZXISHy5jb250ZXN0YW50LnYxLkdldEFuc3dlclJlcXVlc3QaIC5jb250ZXN0YW50LnYxLkdldEFuc3dlclJlc3BvbnNlQsIBChFjb20uY29udGVzdGFudC52MUILQW5zd2VyUHJvdG9QAVpLZ2l0aHViLmNvbS9pY3RzYy9pY3RzYy1yZWdhbGlhL2JhY2tlbmQvcGtnL3Byb3RvL2NvbnRlc3RhbnQvdjE7Y29udGVzdGFudHYxogIDQ1hYqgINQ29udGVzdGFudC5WMcoCDUNvbnRlc3RhbnRcVjHiAhlDb250ZXN0YW50XFYxXEdQQk1ldGFkYXRh6gIOQ29udGVzdGFudDo6VjFiBnByb3RvMw", [file_contestant_v1_problem, file_google_protobuf_duration, file_google_protobuf_timestamp]);

/**
 * Describes the message contestant.v1.Answer.
 * Use `create(AnswerSchema)` to create a new message.
 */
export const AnswerSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 0);

/**
 * Describes the message contestant.v1.AnswerBody.
 * Use `create(AnswerBodySchema)` to create a new message.
 */
export const AnswerBodySchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 1);

/**
 * Describes the message contestant.v1.DescriptiveAnswer.
 * Use `create(DescriptiveAnswerSchema)` to create a new message.
 */
export const DescriptiveAnswerSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 2);

/**
 * Describes the message contestant.v1.ListAnswersRequest.
 * Use `create(ListAnswersRequestSchema)` to create a new message.
 */
export const ListAnswersRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 3);

/**
 * Describes the message contestant.v1.ListAnswersResponse.
 * Use `create(ListAnswersResponseSchema)` to create a new message.
 */
export const ListAnswersResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 4);

/**
 * Describes the message contestant.v1.SubmitAnswerRequest.
 * Use `create(SubmitAnswerRequestSchema)` to create a new message.
 */
export const SubmitAnswerRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 5);

/**
 * Describes the message contestant.v1.SubmitAnswerResponse.
 * Use `create(SubmitAnswerResponseSchema)` to create a new message.
 */
export const SubmitAnswerResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 6);

/**
 * Describes the message contestant.v1.GetAnswerRequest.
 * Use `create(GetAnswerRequestSchema)` to create a new message.
 */
export const GetAnswerRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 7);

/**
 * Describes the message contestant.v1.GetAnswerResponse.
 * Use `create(GetAnswerResponseSchema)` to create a new message.
 */
export const GetAnswerResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_answer, 8);

/**
 * @generated from service contestant.v1.AnswerService
 */
export const AnswerService = /*@__PURE__*/
  serviceDesc(file_contestant_v1_answer, 0);

