// @generated by protoc-gen-es v2.10.2 with parameter "target=js+dts"
// @generated from file contestant/v1/contest.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file contestant/v1/contest.proto.
 */
export declare const file_contestant_v1_contest: GenFile;

/**
 * スケジュールエントリ
 *
 * @generated from message contestant.v1.ScheduleEntry
 */
export declare type ScheduleEntry = Message<"contestant.v1.ScheduleEntry"> & {
  /**
   * スケジュール名(例: "day1-am")
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp start_at = 3;
   */
  startAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp end_at = 4;
   */
  endAt?: Timestamp;
};

/**
 * Describes the message contestant.v1.ScheduleEntry.
 * Use `create(ScheduleEntrySchema)` to create a new message.
 */
export declare const ScheduleEntrySchema: GenMessage<ScheduleEntry>;

/**
 * 現在のコンテスト状態
 *
 * @generated from message contestant.v1.Schedule
 */
export declare type Schedule = Message<"contestant.v1.Schedule"> & {
  /**
   * コンテストが開始済みか（一度でもスケジュールが開始されたか）
   *
   * @generated from field: bool has_started = 2;
   */
  hasStarted: boolean;

  /**
   * 現在アクティブなスケジュール（なければ空）
   *
   * @generated from field: optional contestant.v1.ScheduleEntry current = 3;
   */
  current?: ScheduleEntry;

  /**
   * 次のスケジュール（なければ空）
   *
   * @generated from field: optional contestant.v1.ScheduleEntry next = 4;
   */
  next?: ScheduleEntry;
};

/**
 * Describes the message contestant.v1.Schedule.
 * Use `create(ScheduleSchema)` to create a new message.
 */
export declare const ScheduleSchema: GenMessage<Schedule>;

/**
 * @generated from message contestant.v1.Rule
 */
export declare type Rule = Message<"contestant.v1.Rule"> & {
  /**
   * @generated from field: string markdown = 1;
   */
  markdown: string;
};

/**
 * Describes the message contestant.v1.Rule.
 * Use `create(RuleSchema)` to create a new message.
 */
export declare const RuleSchema: GenMessage<Rule>;

/**
 * @generated from message contestant.v1.GetScheduleRequest
 */
export declare type GetScheduleRequest = Message<"contestant.v1.GetScheduleRequest"> & {
};

/**
 * Describes the message contestant.v1.GetScheduleRequest.
 * Use `create(GetScheduleRequestSchema)` to create a new message.
 */
export declare const GetScheduleRequestSchema: GenMessage<GetScheduleRequest>;

/**
 * @generated from message contestant.v1.GetScheduleResponse
 */
export declare type GetScheduleResponse = Message<"contestant.v1.GetScheduleResponse"> & {
  /**
   * @generated from field: contestant.v1.Schedule schedule = 1;
   */
  schedule?: Schedule;
};

/**
 * Describes the message contestant.v1.GetScheduleResponse.
 * Use `create(GetScheduleResponseSchema)` to create a new message.
 */
export declare const GetScheduleResponseSchema: GenMessage<GetScheduleResponse>;

/**
 * @generated from message contestant.v1.GetRuleRequest
 */
export declare type GetRuleRequest = Message<"contestant.v1.GetRuleRequest"> & {
};

/**
 * Describes the message contestant.v1.GetRuleRequest.
 * Use `create(GetRuleRequestSchema)` to create a new message.
 */
export declare const GetRuleRequestSchema: GenMessage<GetRuleRequest>;

/**
 * @generated from message contestant.v1.GetRuleResponse
 */
export declare type GetRuleResponse = Message<"contestant.v1.GetRuleResponse"> & {
  /**
   * @generated from field: contestant.v1.Rule rule = 1;
   */
  rule?: Rule;
};

/**
 * Describes the message contestant.v1.GetRuleResponse.
 * Use `create(GetRuleResponseSchema)` to create a new message.
 */
export declare const GetRuleResponseSchema: GenMessage<GetRuleResponse>;

/**
 * @generated from service contestant.v1.ContestService
 */
export declare const ContestService: GenService<{
  /**
   * @generated from rpc contestant.v1.ContestService.GetSchedule
   */
  getSchedule: {
    methodKind: "unary";
    input: typeof GetScheduleRequestSchema;
    output: typeof GetScheduleResponseSchema;
  },
  /**
   * @generated from rpc contestant.v1.ContestService.GetRule
   */
  getRule: {
    methodKind: "unary";
    input: typeof GetRuleRequestSchema;
    output: typeof GetRuleResponseSchema;
  },
}>;

