// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file contestant/v1/notice.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file contestant/v1/notice.proto.
 */
export const file_contestant_v1_notice: GenFile = /*@__PURE__*/
  fileDesc("Chpjb250ZXN0YW50L3YxL25vdGljZS5wcm90bxINY29udGVzdGFudC52MSIlCgZOb3RpY2USDQoFdGl0bGUYASABKAkSDAoEYm9keRgCIAEoCSIUChJMaXN0Tm90aWNlc1JlcXVlc3QiPQoTTGlzdE5vdGljZXNSZXNwb25zZRImCgdub3RpY2VzGAEgAygLMhUuY29udGVzdGFudC52MS5Ob3RpY2UyZQoNTm90aWNlU2VydmljZRJUCgtMaXN0Tm90aWNlcxIhLmNvbnRlc3RhbnQudjEuTGlzdE5vdGljZXNSZXF1ZXN0GiIuY29udGVzdGFudC52MS5MaXN0Tm90aWNlc1Jlc3BvbnNlQsIBChFjb20uY29udGVzdGFudC52MUILTm90aWNlUHJvdG9QAVpLZ2l0aHViLmNvbS9pY3RzYy9pY3RzYy1yZWdhbGlhL2JhY2tlbmQvcGtnL3Byb3RvL2NvbnRlc3RhbnQvdjE7Y29udGVzdGFudHYxogIDQ1hYqgINQ29udGVzdGFudC5WMcoCDUNvbnRlc3RhbnRcVjHiAhlDb250ZXN0YW50XFYxXEdQQk1ldGFkYXRh6gIOQ29udGVzdGFudDo6VjFiBnByb3RvMw");

/**
 * @generated from message contestant.v1.Notice
 */
export type Notice = Message<"contestant.v1.Notice"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string body = 2;
   */
  body: string;
};

/**
 * Describes the message contestant.v1.Notice.
 * Use `create(NoticeSchema)` to create a new message.
 */
export const NoticeSchema: GenMessage<Notice> = /*@__PURE__*/
  messageDesc(file_contestant_v1_notice, 0);

/**
 * @generated from message contestant.v1.ListNoticesRequest
 */
export type ListNoticesRequest = Message<"contestant.v1.ListNoticesRequest"> & {
};

/**
 * Describes the message contestant.v1.ListNoticesRequest.
 * Use `create(ListNoticesRequestSchema)` to create a new message.
 */
export const ListNoticesRequestSchema: GenMessage<ListNoticesRequest> = /*@__PURE__*/
  messageDesc(file_contestant_v1_notice, 1);

/**
 * @generated from message contestant.v1.ListNoticesResponse
 */
export type ListNoticesResponse = Message<"contestant.v1.ListNoticesResponse"> & {
  /**
   * @generated from field: repeated contestant.v1.Notice notices = 1;
   */
  notices: Notice[];
};

/**
 * Describes the message contestant.v1.ListNoticesResponse.
 * Use `create(ListNoticesResponseSchema)` to create a new message.
 */
export const ListNoticesResponseSchema: GenMessage<ListNoticesResponse> = /*@__PURE__*/
  messageDesc(file_contestant_v1_notice, 2);

/**
 * @generated from service contestant.v1.NoticeService
 */
export const NoticeService: GenService<{
  /**
   * @generated from rpc contestant.v1.NoticeService.ListNotices
   */
  listNotices: {
    methodKind: "unary";
    input: typeof ListNoticesRequestSchema;
    output: typeof ListNoticesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_contestant_v1_notice, 0);

