// @generated by protoc-gen-es v2.10.2 with parameter "target=js+dts"
// @generated from file contestant/v1/profile.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file contestant/v1/profile.proto.
 */
export declare const file_contestant_v1_profile: GenFile;

/**
 * @generated from message contestant.v1.TeamProfile
 */
export declare type TeamProfile = Message<"contestant.v1.TeamProfile"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string organization = 2;
   */
  organization: string;

  /**
   * @generated from field: repeated contestant.v1.ContestantProfile members = 3;
   */
  members: ContestantProfile[];
};

/**
 * Describes the message contestant.v1.TeamProfile.
 * Use `create(TeamProfileSchema)` to create a new message.
 */
export declare const TeamProfileSchema: GenMessage<TeamProfile>;

/**
 * @generated from message contestant.v1.ContestantProfile
 */
export declare type ContestantProfile = Message<"contestant.v1.ContestantProfile"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * @generated from field: string self_introduction = 3;
   */
  selfIntroduction: string;
};

/**
 * Describes the message contestant.v1.ContestantProfile.
 * Use `create(ContestantProfileSchema)` to create a new message.
 */
export declare const ContestantProfileSchema: GenMessage<ContestantProfile>;

/**
 * @generated from message contestant.v1.ListTeamsRequest
 */
export declare type ListTeamsRequest = Message<"contestant.v1.ListTeamsRequest"> & {
};

/**
 * Describes the message contestant.v1.ListTeamsRequest.
 * Use `create(ListTeamsRequestSchema)` to create a new message.
 */
export declare const ListTeamsRequestSchema: GenMessage<ListTeamsRequest>;

/**
 * @generated from message contestant.v1.ListTeamsResponse
 */
export declare type ListTeamsResponse = Message<"contestant.v1.ListTeamsResponse"> & {
  /**
   * @generated from field: repeated contestant.v1.TeamProfile teams = 1;
   */
  teams: TeamProfile[];
};

/**
 * Describes the message contestant.v1.ListTeamsResponse.
 * Use `create(ListTeamsResponseSchema)` to create a new message.
 */
export declare const ListTeamsResponseSchema: GenMessage<ListTeamsResponse>;

/**
 * @generated from message contestant.v1.UpdateProfileRequest
 */
export declare type UpdateProfileRequest = Message<"contestant.v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: contestant.v1.ContestantProfile profile = 1;
   */
  profile?: ContestantProfile;
};

/**
 * Describes the message contestant.v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export declare const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest>;

/**
 * @generated from message contestant.v1.UpdateProfileResponse
 */
export declare type UpdateProfileResponse = Message<"contestant.v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: contestant.v1.ContestantProfile profile = 1;
   */
  profile?: ContestantProfile;
};

/**
 * Describes the message contestant.v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export declare const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse>;

/**
 * @generated from service contestant.v1.ProfileService
 */
export declare const ProfileService: GenService<{
  /**
   * @generated from rpc contestant.v1.ProfileService.ListTeams
   */
  listTeams: {
    methodKind: "unary";
    input: typeof ListTeamsRequestSchema;
    output: typeof ListTeamsResponseSchema;
  },
  /**
   * @generated from rpc contestant.v1.ProfileService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  },
}>;

