// @generated by protoc-gen-es v2.8.0 with parameter "target=js+dts"
// @generated from file contestant/v1/ranking.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file contestant/v1/ranking.proto.
 */
export const file_contestant_v1_ranking = /*@__PURE__*/
  fileDesc("Chtjb250ZXN0YW50L3YxL3JhbmtpbmcucHJvdG8SDWNvbnRlc3RhbnQudjEiewoEUmFuaxIMCgRyYW5rGAEgASgDEhEKCXRlYW1fbmFtZRgCIAEoCRINCgVzY29yZRgDIAEoAxItCgl0aW1lc3RhbXAYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhQKDG9yZ2FuaXphdGlvbhgFIAEoCSITChFHZXRSYW5raW5nUmVxdWVzdCI6ChJHZXRSYW5raW5nUmVzcG9uc2USJAoHcmFua2luZxgBIAMoCzITLmNvbnRlc3RhbnQudjEuUmFuazJjCg5SYW5raW5nU2VydmljZRJRCgpHZXRSYW5raW5nEiAuY29udGVzdGFudC52MS5HZXRSYW5raW5nUmVxdWVzdBohLmNvbnRlc3RhbnQudjEuR2V0UmFua2luZ1Jlc3BvbnNlQsMBChFjb20uY29udGVzdGFudC52MUIMUmFua2luZ1Byb3RvUAFaS2dpdGh1Yi5jb20vaWN0c2MvaWN0c2MtcmVnYWxpYS9iYWNrZW5kL3BrZy9wcm90by9jb250ZXN0YW50L3YxO2NvbnRlc3RhbnR2MaICA0NYWKoCDUNvbnRlc3RhbnQuVjHKAg1Db250ZXN0YW50XFYx4gIZQ29udGVzdGFudFxWMVxHUEJNZXRhZGF0YeoCDkNvbnRlc3RhbnQ6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * Describes the message contestant.v1.Rank.
 * Use `create(RankSchema)` to create a new message.
 */
export const RankSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_ranking, 0);

/**
 * Describes the message contestant.v1.GetRankingRequest.
 * Use `create(GetRankingRequestSchema)` to create a new message.
 */
export const GetRankingRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_ranking, 1);

/**
 * Describes the message contestant.v1.GetRankingResponse.
 * Use `create(GetRankingResponseSchema)` to create a new message.
 */
export const GetRankingResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_ranking, 2);

/**
 * @generated from service contestant.v1.RankingService
 */
export const RankingService = /*@__PURE__*/
  serviceDesc(file_contestant_v1_ranking, 0);

