// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file contestant/v1/viewer.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file contestant/v1/viewer.proto.
 */
export const file_contestant_v1_viewer: GenFile = /*@__PURE__*/
  fileDesc("Chpjb250ZXN0YW50L3YxL3ZpZXdlci5wcm90bxINY29udGVzdGFudC52MSIWCgZWaWV3ZXISDAoEbmFtZRgBIAEoCSISChBHZXRWaWV3ZXJSZXF1ZXN0IkIKEUdldFZpZXdlclJlc3BvbnNlEi0KBnZpZXdlchgBIAEoCzIVLmNvbnRlc3RhbnQudjEuVmlld2VyQga6SAPIAQEyXwoNVmlld2VyU2VydmljZRJOCglHZXRWaWV3ZXISHy5jb250ZXN0YW50LnYxLkdldFZpZXdlclJlcXVlc3QaIC5jb250ZXN0YW50LnYxLkdldFZpZXdlclJlc3BvbnNlQsIBChFjb20uY29udGVzdGFudC52MUILVmlld2VyUHJvdG9QAVpLZ2l0aHViLmNvbS9pY3RzYy9pY3RzYy1yZWdhbGlhL2JhY2tlbmQvcGtnL3Byb3RvL2NvbnRlc3RhbnQvdjE7Y29udGVzdGFudHYxogIDQ1hYqgINQ29udGVzdGFudC5WMcoCDUNvbnRlc3RhbnRcVjHiAhlDb250ZXN0YW50XFYxXEdQQk1ldGFkYXRh6gIOQ29udGVzdGFudDo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message contestant.v1.Viewer
 */
export type Viewer = Message<"contestant.v1.Viewer"> & {
  /**
   * TODO: チームに関する情報が必要
   * コードかチーム自体か
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message contestant.v1.Viewer.
 * Use `create(ViewerSchema)` to create a new message.
 */
export const ViewerSchema: GenMessage<Viewer> = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 0);

/**
 * @generated from message contestant.v1.GetViewerRequest
 */
export type GetViewerRequest = Message<"contestant.v1.GetViewerRequest"> & {
};

/**
 * Describes the message contestant.v1.GetViewerRequest.
 * Use `create(GetViewerRequestSchema)` to create a new message.
 */
export const GetViewerRequestSchema: GenMessage<GetViewerRequest> = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 1);

/**
 * @generated from message contestant.v1.GetViewerResponse
 */
export type GetViewerResponse = Message<"contestant.v1.GetViewerResponse"> & {
  /**
   * @generated from field: contestant.v1.Viewer viewer = 1;
   */
  viewer?: Viewer;
};

/**
 * Describes the message contestant.v1.GetViewerResponse.
 * Use `create(GetViewerResponseSchema)` to create a new message.
 */
export const GetViewerResponseSchema: GenMessage<GetViewerResponse> = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 2);

/**
 * @generated from service contestant.v1.ViewerService
 */
export const ViewerService: GenService<{
  /**
   * @generated from rpc contestant.v1.ViewerService.GetViewer
   */
  getViewer: {
    methodKind: "unary";
    input: typeof GetViewerRequestSchema;
    output: typeof GetViewerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_contestant_v1_viewer, 0);

