// @generated by protoc-gen-es v2.8.0 with parameter "target=js+dts"
// @generated from file contestant/v1/viewer.proto (package contestant.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";

/**
 * Describes the file contestant/v1/viewer.proto.
 */
export const file_contestant_v1_viewer = /*@__PURE__*/
  fileDesc("Chpjb250ZXN0YW50L3YxL3ZpZXdlci5wcm90bxINY29udGVzdGFudC52MSKwAQoGVmlld2VyEgwKBG5hbWUYASABKAkSJwoEdHlwZRgCIAEoDjIZLmNvbnRlc3RhbnQudjEuVmlld2VyVHlwZRI1Cgpjb250ZXN0YW50GAMgASgLMh8uY29udGVzdGFudC52MS5Db250ZXN0YW50Vmlld2VySAASLgoHc2lnbl91cBgEIAEoCzIbLmNvbnRlc3RhbnQudjEuU2lnblVwVmlld2VySABCCAoGdmlld2VyIjYKEENvbnRlc3RhbnRWaWV3ZXISDAoEbmFtZRgBIAEoCRIUCgxkaXNwbGF5X25hbWUYAiABKAkiMgoMU2lnblVwVmlld2VyEgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJIhIKEEdldFZpZXdlclJlcXVlc3QiQgoRR2V0Vmlld2VyUmVzcG9uc2USLQoGdmlld2VyGAEgASgLMhUuY29udGVzdGFudC52MS5WaWV3ZXJCBrpIA8gBASJMCg1TaWduVXBSZXF1ZXN0EgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhcKD2ludml0YXRpb25fY29kZRgDIAEoCSIQCg5TaWduVXBSZXNwb25zZSpeCgpWaWV3ZXJUeXBlEhsKF1ZJRVdFUl9UWVBFX1VOU1BFQ0lGSUVEEAASGgoWVklFV0VSX1RZUEVfQ09OVEVTVEFOVBABEhcKE1ZJRVdFUl9UWVBFX1NJR05fVVAQAjKmAQoNVmlld2VyU2VydmljZRJOCglHZXRWaWV3ZXISHy5jb250ZXN0YW50LnYxLkdldFZpZXdlclJlcXVlc3QaIC5jb250ZXN0YW50LnYxLkdldFZpZXdlclJlc3BvbnNlEkUKBlNpZ25VcBIcLmNvbnRlc3RhbnQudjEuU2lnblVwUmVxdWVzdBodLmNvbnRlc3RhbnQudjEuU2lnblVwUmVzcG9uc2VCwgEKEWNvbS5jb250ZXN0YW50LnYxQgtWaWV3ZXJQcm90b1ABWktnaXRodWIuY29tL2ljdHNjL2ljdHNjLXJlZ2FsaWEvYmFja2VuZC9wa2cvcHJvdG8vY29udGVzdGFudC92MTtjb250ZXN0YW50djGiAgNDWFiqAg1Db250ZXN0YW50LlYxygINQ29udGVzdGFudFxWMeICGUNvbnRlc3RhbnRcVjFcR1BCTWV0YWRhdGHqAg5Db250ZXN0YW50OjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Describes the message contestant.v1.Viewer.
 * Use `create(ViewerSchema)` to create a new message.
 */
export const ViewerSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 0);

/**
 * Describes the message contestant.v1.ContestantViewer.
 * Use `create(ContestantViewerSchema)` to create a new message.
 */
export const ContestantViewerSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 1);

/**
 * Describes the message contestant.v1.SignUpViewer.
 * Use `create(SignUpViewerSchema)` to create a new message.
 */
export const SignUpViewerSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 2);

/**
 * Describes the message contestant.v1.GetViewerRequest.
 * Use `create(GetViewerRequestSchema)` to create a new message.
 */
export const GetViewerRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 3);

/**
 * Describes the message contestant.v1.GetViewerResponse.
 * Use `create(GetViewerResponseSchema)` to create a new message.
 */
export const GetViewerResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 4);

/**
 * Describes the message contestant.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 5);

/**
 * Describes the message contestant.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_contestant_v1_viewer, 6);

/**
 * Describes the enum contestant.v1.ViewerType.
 */
export const ViewerTypeSchema = /*@__PURE__*/
  enumDesc(file_contestant_v1_viewer, 0);

/**
 * @generated from enum contestant.v1.ViewerType
 */
export const ViewerType = /*@__PURE__*/
  tsEnum(ViewerTypeSchema);

/**
 * @generated from service contestant.v1.ViewerService
 */
export const ViewerService = /*@__PURE__*/
  serviceDesc(file_contestant_v1_viewer, 0);

