// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: contestant/v1/ranking.proto

package contestantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	TeamName      string                 `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Organization  string                 `protobuf:"bytes,5,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rank) Reset() {
	*x = Rank{}
	mi := &file_contestant_v1_ranking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_ranking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_contestant_v1_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *Rank) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Rank) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *Rank) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rank) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Rank) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type GetRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingRequest) Reset() {
	*x = GetRankingRequest{}
	mi := &file_contestant_v1_ranking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingRequest) ProtoMessage() {}

func (x *GetRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_ranking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingRequest.ProtoReflect.Descriptor instead.
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return file_contestant_v1_ranking_proto_rawDescGZIP(), []int{1}
}

type GetRankingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranking       []*Rank                `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingResponse) Reset() {
	*x = GetRankingResponse{}
	mi := &file_contestant_v1_ranking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingResponse) ProtoMessage() {}

func (x *GetRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_ranking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingResponse.ProtoReflect.Descriptor instead.
func (*GetRankingResponse) Descriptor() ([]byte, []int) {
	return file_contestant_v1_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *GetRankingResponse) GetRanking() []*Rank {
	if x != nil {
		return x.Ranking
	}
	return nil
}

var File_contestant_v1_ranking_proto protoreflect.FileDescriptor

const file_contestant_v1_ranking_proto_rawDesc = "" +
	"\n" +
	"\x1bcontestant/v1/ranking.proto\x12\rcontestant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x04Rank\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12\x1b\n" +
	"\tteam_name\x18\x02 \x01(\tR\bteamName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\"\n" +
	"\forganization\x18\x05 \x01(\tR\forganization\"\x13\n" +
	"\x11GetRankingRequest\"C\n" +
	"\x12GetRankingResponse\x12-\n" +
	"\aranking\x18\x01 \x03(\v2\x13.contestant.v1.RankR\aranking2c\n" +
	"\x0eRankingService\x12Q\n" +
	"\n" +
	"GetRanking\x12 .contestant.v1.GetRankingRequest\x1a!.contestant.v1.GetRankingResponseBMZKgithub.com/ictsc/ictsc-regalia/backend/pkg/proto/contestant/v1;contestantv1b\x06proto3"

var (
	file_contestant_v1_ranking_proto_rawDescOnce sync.Once
	file_contestant_v1_ranking_proto_rawDescData []byte
)

func file_contestant_v1_ranking_proto_rawDescGZIP() []byte {
	file_contestant_v1_ranking_proto_rawDescOnce.Do(func() {
		file_contestant_v1_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contestant_v1_ranking_proto_rawDesc), len(file_contestant_v1_ranking_proto_rawDesc)))
	})
	return file_contestant_v1_ranking_proto_rawDescData
}

var file_contestant_v1_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contestant_v1_ranking_proto_goTypes = []any{
	(*Rank)(nil),                  // 0: contestant.v1.Rank
	(*GetRankingRequest)(nil),     // 1: contestant.v1.GetRankingRequest
	(*GetRankingResponse)(nil),    // 2: contestant.v1.GetRankingResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_contestant_v1_ranking_proto_depIdxs = []int32{
	3, // 0: contestant.v1.Rank.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: contestant.v1.GetRankingResponse.ranking:type_name -> contestant.v1.Rank
	1, // 2: contestant.v1.RankingService.GetRanking:input_type -> contestant.v1.GetRankingRequest
	2, // 3: contestant.v1.RankingService.GetRanking:output_type -> contestant.v1.GetRankingResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contestant_v1_ranking_proto_init() }
func file_contestant_v1_ranking_proto_init() {
	if File_contestant_v1_ranking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contestant_v1_ranking_proto_rawDesc), len(file_contestant_v1_ranking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contestant_v1_ranking_proto_goTypes,
		DependencyIndexes: file_contestant_v1_ranking_proto_depIdxs,
		MessageInfos:      file_contestant_v1_ranking_proto_msgTypes,
	}.Build()
	File_contestant_v1_ranking_proto = out.File
	file_contestant_v1_ranking_proto_goTypes = nil
	file_contestant_v1_ranking_proto_depIdxs = nil
}
