// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: contestant/v1/viewer.proto

package contestantv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewerType int32

const (
	ViewerType_VIEWER_TYPE_UNSPECIFIED ViewerType = 0
	ViewerType_VIEWER_TYPE_CONTESTANT  ViewerType = 1
	ViewerType_VIEWER_TYPE_SIGN_UP     ViewerType = 2
)

// Enum value maps for ViewerType.
var (
	ViewerType_name = map[int32]string{
		0: "VIEWER_TYPE_UNSPECIFIED",
		1: "VIEWER_TYPE_CONTESTANT",
		2: "VIEWER_TYPE_SIGN_UP",
	}
	ViewerType_value = map[string]int32{
		"VIEWER_TYPE_UNSPECIFIED": 0,
		"VIEWER_TYPE_CONTESTANT":  1,
		"VIEWER_TYPE_SIGN_UP":     2,
	}
)

func (x ViewerType) Enum() *ViewerType {
	p := new(ViewerType)
	*p = x
	return p
}

func (x ViewerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewerType) Descriptor() protoreflect.EnumDescriptor {
	return file_contestant_v1_viewer_proto_enumTypes[0].Descriptor()
}

func (ViewerType) Type() protoreflect.EnumType {
	return &file_contestant_v1_viewer_proto_enumTypes[0]
}

func (x ViewerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewerType.Descriptor instead.
func (ViewerType) EnumDescriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{0}
}

type Viewer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  ViewerType             `protobuf:"varint,2,opt,name=type,proto3,enum=contestant.v1.ViewerType" json:"type,omitempty"`
	// Types that are valid to be assigned to Viewer:
	//
	//	*Viewer_Contestant
	//	*Viewer_SignUp
	Viewer        isViewer_Viewer `protobuf_oneof:"viewer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewer) Reset() {
	*x = Viewer{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewer) ProtoMessage() {}

func (x *Viewer) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewer.ProtoReflect.Descriptor instead.
func (*Viewer) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *Viewer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Viewer) GetType() ViewerType {
	if x != nil {
		return x.Type
	}
	return ViewerType_VIEWER_TYPE_UNSPECIFIED
}

func (x *Viewer) GetViewer() isViewer_Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

func (x *Viewer) GetContestant() *ContestantViewer {
	if x != nil {
		if x, ok := x.Viewer.(*Viewer_Contestant); ok {
			return x.Contestant
		}
	}
	return nil
}

func (x *Viewer) GetSignUp() *SignUpViewer {
	if x != nil {
		if x, ok := x.Viewer.(*Viewer_SignUp); ok {
			return x.SignUp
		}
	}
	return nil
}

type isViewer_Viewer interface {
	isViewer_Viewer()
}

type Viewer_Contestant struct {
	Contestant *ContestantViewer `protobuf:"bytes,3,opt,name=contestant,proto3,oneof"`
}

type Viewer_SignUp struct {
	SignUp *SignUpViewer `protobuf:"bytes,4,opt,name=sign_up,json=signUp,proto3,oneof"`
}

func (*Viewer_Contestant) isViewer_Viewer() {}

func (*Viewer_SignUp) isViewer_Viewer() {}

type ContestantViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestantViewer) Reset() {
	*x = ContestantViewer{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestantViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestantViewer) ProtoMessage() {}

func (x *ContestantViewer) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestantViewer.ProtoReflect.Descriptor instead.
func (*ContestantViewer) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{1}
}

func (x *ContestantViewer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContestantViewer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// サインアップ中のユーザ
type SignUpViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpViewer) Reset() {
	*x = SignUpViewer{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpViewer) ProtoMessage() {}

func (x *SignUpViewer) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpViewer.ProtoReflect.Descriptor instead.
func (*SignUpViewer) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpViewer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpViewer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetViewerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerRequest) Reset() {
	*x = GetViewerRequest{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerRequest) ProtoMessage() {}

func (x *GetViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerRequest.ProtoReflect.Descriptor instead.
func (*GetViewerRequest) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{3}
}

type GetViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Viewer        *Viewer                `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetViewerResponse) Reset() {
	*x = GetViewerResponse{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewerResponse) ProtoMessage() {}

func (x *GetViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewerResponse.ProtoReflect.Descriptor instead.
func (*GetViewerResponse) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{4}
}

func (x *GetViewerResponse) GetViewer() *Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

type SignUpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	InvitationCode string                 `protobuf:"bytes,3,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SignUpRequest) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_contestant_v1_viewer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contestant_v1_viewer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_contestant_v1_viewer_proto_rawDescGZIP(), []int{6}
}

var File_contestant_v1_viewer_proto protoreflect.FileDescriptor

var file_contestant_v1_viewer_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x06, 0x56, 0x69, 0x65,
	0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x69, 0x67,
	0x6e, 0x5f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x42, 0x08, 0x0a, 0x06, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x10, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x42, 0x06, 0xba,
	0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x06, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x22, 0x6f, 0x0a,
	0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x10,
	0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2a, 0x5e, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x56,
	0x49, 0x45, 0x57, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45,
	0x53, 0x54, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x56, 0x49, 0x45, 0x57, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x55, 0x50, 0x10, 0x02,
	0x32, 0xa6, 0x01, 0x0a, 0x0d, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x12,
	0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x1c, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x63, 0x74, 0x73, 0x63, 0x2f, 0x69, 0x63,
	0x74, 0x73, 0x63, 0x2d, 0x72, 0x65, 0x67, 0x61, 0x6c, 0x69, 0x61, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_contestant_v1_viewer_proto_rawDescOnce sync.Once
	file_contestant_v1_viewer_proto_rawDescData []byte
)

func file_contestant_v1_viewer_proto_rawDescGZIP() []byte {
	file_contestant_v1_viewer_proto_rawDescOnce.Do(func() {
		file_contestant_v1_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contestant_v1_viewer_proto_rawDesc), len(file_contestant_v1_viewer_proto_rawDesc)))
	})
	return file_contestant_v1_viewer_proto_rawDescData
}

var file_contestant_v1_viewer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contestant_v1_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_contestant_v1_viewer_proto_goTypes = []any{
	(ViewerType)(0),           // 0: contestant.v1.ViewerType
	(*Viewer)(nil),            // 1: contestant.v1.Viewer
	(*ContestantViewer)(nil),  // 2: contestant.v1.ContestantViewer
	(*SignUpViewer)(nil),      // 3: contestant.v1.SignUpViewer
	(*GetViewerRequest)(nil),  // 4: contestant.v1.GetViewerRequest
	(*GetViewerResponse)(nil), // 5: contestant.v1.GetViewerResponse
	(*SignUpRequest)(nil),     // 6: contestant.v1.SignUpRequest
	(*SignUpResponse)(nil),    // 7: contestant.v1.SignUpResponse
}
var file_contestant_v1_viewer_proto_depIdxs = []int32{
	0, // 0: contestant.v1.Viewer.type:type_name -> contestant.v1.ViewerType
	2, // 1: contestant.v1.Viewer.contestant:type_name -> contestant.v1.ContestantViewer
	3, // 2: contestant.v1.Viewer.sign_up:type_name -> contestant.v1.SignUpViewer
	1, // 3: contestant.v1.GetViewerResponse.viewer:type_name -> contestant.v1.Viewer
	4, // 4: contestant.v1.ViewerService.GetViewer:input_type -> contestant.v1.GetViewerRequest
	6, // 5: contestant.v1.ViewerService.SignUp:input_type -> contestant.v1.SignUpRequest
	5, // 6: contestant.v1.ViewerService.GetViewer:output_type -> contestant.v1.GetViewerResponse
	7, // 7: contestant.v1.ViewerService.SignUp:output_type -> contestant.v1.SignUpResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contestant_v1_viewer_proto_init() }
func file_contestant_v1_viewer_proto_init() {
	if File_contestant_v1_viewer_proto != nil {
		return
	}
	file_contestant_v1_viewer_proto_msgTypes[0].OneofWrappers = []any{
		(*Viewer_Contestant)(nil),
		(*Viewer_SignUp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contestant_v1_viewer_proto_rawDesc), len(file_contestant_v1_viewer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contestant_v1_viewer_proto_goTypes,
		DependencyIndexes: file_contestant_v1_viewer_proto_depIdxs,
		EnumInfos:         file_contestant_v1_viewer_proto_enumTypes,
		MessageInfos:      file_contestant_v1_viewer_proto_msgTypes,
	}.Build()
	File_contestant_v1_viewer_proto = out.File
	file_contestant_v1_viewer_proto_goTypes = nil
	file_contestant_v1_viewer_proto_depIdxs = nil
}
