resources:
  - ../../base

namespace: scoreserver

images:
  - name: backend
    newName: ghcr.io/ictsc/ictsc-regalia/backend
    newTag: prod
  - name: frontend
    newName: ghcr.io/ictsc/ictsc-regalia/frontend
    newTag: prod

patches:
  - path: httproute-patch.yaml

replicas:
  - name: scoreserver-backend
    count: 2
  - name: scoreserver-frontend
    count: 2
