name: Setup Go
description: Setup Go environment with repository specific settings.
runs:
  using: composite
  steps:
    - name: Setup Go Toolchain
      uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false
    - name: Restore Module Cache
      uses: actions/cache/restore@v4
      id: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: go-mod-${{ hashFiles('backend/go.sum') }}
        restore-keys: |
          go-mod-
    - name: Clean large module cache
      if: >-
        steps.go-mod-cache.outputs.cache-hit != 'true'
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      run: |
        CACHE_SIZE=$(du -sm ~/go/pkg/mod 2>/dev/null | cut -f1 || echo "0")
        if [ "$CACHE_SIZE" -gt 200 ]; then
          go clean -modcache
        fi
      shell: bash
    - name: Download Go Modules
      if: steps.go-mod-cache.outputs.cache-hit != 'true'
      run: go mod download
      working-directory: backend
      shell: bash
    - name: Save Module Cache
      if: >-
        steps.go-mod-cache.outputs.cache-hit != 'true'
        && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: actions/cache/save@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ steps.go-mod-cache.outputs.cache-primary-key }}
