openapi: 3.0.3
info:
  title: ictsc-outlands contestant.v1 file API
  description: ictsc-outlands contestant.v1 file API
  version: "1.0"
  contact:
    name: ictsc
    url: "https://github.com/ictsc/ictsc-outlands"
servers:
  - url: "https://contest.ictsc.net/api"
    description: prod
  - url: "https://contest-dev.ictsc.net/api"
    description: dev
tags:
  - name: file
    description: ファイルAPI
paths:
  /files:
    post:
      summary: ファイルをアップロード
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: ulid
                required:
                  - id
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "413":
          description: Too Large File
        "500":
          description: Internal Server Error
      tags:
        - file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      operationId: postFile
      description: |-
        ファイルをアップロードします。
  /files/{fileId}:
    parameters:
      - name: fileId
        in: path
        required: true
        description: ファイルULID
        schema:
          type: string
          format: ulid
    get:
      summary: ファイルをダウンロード
      tags:
        - file
      responses:
        "200":
          description: |-
            OK
            ファイル本体を返します。
            application/octet-streamで返すことになっていますが、ファイルの形式によって変わります。
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      operationId: getFile
      description: |-
        指定したファイルを取得します。
