/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/~__root";
import { Route as IndexRouteImport } from "./routes/~index";
import { Route as SubmissionsIndexRouteRouteImport } from "./routes/~submissions.index/~route";
import { Route as SubmissionsProblemTeamIdRouteRouteImport } from "./routes/~submissions.$problem.$team.$id/~route";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SubmissionsIndexRouteRoute = SubmissionsIndexRouteRouteImport.update({
  id: "/submissions/",
  path: "/submissions",
  getParentRoute: () => rootRouteImport,
} as any);
const SubmissionsProblemTeamIdRouteRoute =
  SubmissionsProblemTeamIdRouteRouteImport.update({
    id: "/submissions/$problem/$team/$id",
    path: "/submissions/$problem/$team/$id",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/submissions": typeof SubmissionsIndexRouteRoute;
  "/submissions/$problem/$team/$id": typeof SubmissionsProblemTeamIdRouteRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/submissions": typeof SubmissionsIndexRouteRoute;
  "/submissions/$problem/$team/$id": typeof SubmissionsProblemTeamIdRouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/submissions/": typeof SubmissionsIndexRouteRoute;
  "/submissions/$problem/$team/$id": typeof SubmissionsProblemTeamIdRouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/submissions" | "/submissions/$problem/$team/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/submissions" | "/submissions/$problem/$team/$id";
  id: "__root__" | "/" | "/submissions/" | "/submissions/$problem/$team/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SubmissionsIndexRouteRoute: typeof SubmissionsIndexRouteRoute;
  SubmissionsProblemTeamIdRouteRoute: typeof SubmissionsProblemTeamIdRouteRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/submissions/": {
      id: "/submissions/";
      path: "/submissions";
      fullPath: "/submissions";
      preLoaderRoute: typeof SubmissionsIndexRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/submissions/$problem/$team/$id": {
      id: "/submissions/$problem/$team/$id";
      path: "/submissions/$problem/$team/$id";
      fullPath: "/submissions/$problem/$team/$id";
      preLoaderRoute: typeof SubmissionsProblemTeamIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubmissionsIndexRouteRoute: SubmissionsIndexRouteRoute,
  SubmissionsProblemTeamIdRouteRoute: SubmissionsProblemTeamIdRouteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
