// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file anita/v1/user.proto (package anita.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file anita/v1/user.proto.
 */
export const file_anita_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChNhbml0YS92MS91c2VyLnByb3RvEghhbml0YS52MSJQCgRVc2VyEhQKAmlkGAEgASgJQgi6SAVyA5gBGhIXCgRuYW1lGAIgASgJQgm6SAZyBBABGBQSGQoHdGVhbV9pZBgDIAEoCUIIukgFcgOYARoiJgoOR2V0VXNlclJlcXVlc3QSFAoCaWQYASABKAlCCLpIBXIDmAEaIjcKD0dldFVzZXJSZXNwb25zZRIkCgR1c2VyGAEgASgLMg4uYW5pdGEudjEuVXNlckIGukgDyAEBIhEKD0dldFVzZXJzUmVxdWVzdCI5ChBHZXRVc2Vyc1Jlc3BvbnNlEiUKBXVzZXJzGAEgAygLMg4uYW5pdGEudjEuVXNlckIGukgDyAEBImMKD1Bvc3RVc2VyUmVxdWVzdBIUCgJpZBgBIAEoCUIIukgFcgOYARoSFwoEbmFtZRgCIAEoCUIJukgGcgQQARgUEiEKD2ludml0YXRpb25fY29kZRgDIAEoCUIIukgFcgOYASAiOAoQUG9zdFVzZXJSZXNwb25zZRIkCgR1c2VyGAEgASgLMg4uYW5pdGEudjEuVXNlckIGukgDyAEBIkEKEFBhdGNoVXNlclJlcXVlc3QSFAoCaWQYASABKAlCCLpIBXIDmAEaEhcKBG5hbWUYAiABKAlCCbpIBnIEEAEYFCI5ChFQYXRjaFVzZXJSZXNwb25zZRIkCgR1c2VyGAEgASgLMg4uYW5pdGEudjEuVXNlckIGukgDyAEBIikKEURlbGV0ZVVzZXJSZXF1ZXN0EhQKAmlkGAEgASgJQgi6SAVyA5gBGiIUChJEZWxldGVVc2VyUmVzcG9uc2Uy7AIKC1VzZXJTZXJ2aWNlEkAKB0dldFVzZXISGC5hbml0YS52MS5HZXRVc2VyUmVxdWVzdBoZLmFuaXRhLnYxLkdldFVzZXJSZXNwb25zZSIAEkMKCEdldFVzZXJzEhkuYW5pdGEudjEuR2V0VXNlcnNSZXF1ZXN0GhouYW5pdGEudjEuR2V0VXNlcnNSZXNwb25zZSIAEkMKCFBvc3RVc2VyEhkuYW5pdGEudjEuUG9zdFVzZXJSZXF1ZXN0GhouYW5pdGEudjEuUG9zdFVzZXJSZXNwb25zZSIAEkYKCVBhdGNoVXNlchIaLmFuaXRhLnYxLlBhdGNoVXNlclJlcXVlc3QaGy5hbml0YS52MS5QYXRjaFVzZXJSZXNwb25zZSIAEkkKCkRlbGV0ZVVzZXISGy5hbml0YS52MS5EZWxldGVVc2VyUmVxdWVzdBocLmFuaXRhLnYxLkRlbGV0ZVVzZXJSZXNwb25zZSIAQpsBCgxjb20uYW5pdGEudjFCCVVzZXJQcm90b1ABWj9naXRodWIuY29tL2ljdHNjL2ljdHNjLW91dGxhbmRzL2JhY2tlbmQvaW50ZXJuYWwvcHJvdG8vYW5pdGEvdjGiAgNBWFiqAghBbml0YS5WMcoCCEFuaXRhXFYx4gIUQW5pdGFcVjFcR1BCTWV0YWRhdGHqAglBbml0YTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message anita.v1.User
 */
export type User = Message<"anita.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string team_id = 3;
   */
  teamId: string;
};

/**
 * Describes the message anita.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 0);

/**
 * @generated from message anita.v1.GetUserRequest
 */
export type GetUserRequest = Message<"anita.v1.GetUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message anita.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 1);

/**
 * @generated from message anita.v1.GetUserResponse
 */
export type GetUserResponse = Message<"anita.v1.GetUserResponse"> & {
  /**
   * @generated from field: anita.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message anita.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 2);

/**
 * @generated from message anita.v1.GetUsersRequest
 */
export type GetUsersRequest = Message<"anita.v1.GetUsersRequest"> & {
};

/**
 * Describes the message anita.v1.GetUsersRequest.
 * Use `create(GetUsersRequestSchema)` to create a new message.
 */
export const GetUsersRequestSchema: GenMessage<GetUsersRequest> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 3);

/**
 * @generated from message anita.v1.GetUsersResponse
 */
export type GetUsersResponse = Message<"anita.v1.GetUsersResponse"> & {
  /**
   * @generated from field: repeated anita.v1.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message anita.v1.GetUsersResponse.
 * Use `create(GetUsersResponseSchema)` to create a new message.
 */
export const GetUsersResponseSchema: GenMessage<GetUsersResponse> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 4);

/**
 * @generated from message anita.v1.PostUserRequest
 */
export type PostUserRequest = Message<"anita.v1.PostUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string invitation_code = 3;
   */
  invitationCode: string;
};

/**
 * Describes the message anita.v1.PostUserRequest.
 * Use `create(PostUserRequestSchema)` to create a new message.
 */
export const PostUserRequestSchema: GenMessage<PostUserRequest> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 5);

/**
 * @generated from message anita.v1.PostUserResponse
 */
export type PostUserResponse = Message<"anita.v1.PostUserResponse"> & {
  /**
   * @generated from field: anita.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message anita.v1.PostUserResponse.
 * Use `create(PostUserResponseSchema)` to create a new message.
 */
export const PostUserResponseSchema: GenMessage<PostUserResponse> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 6);

/**
 * @generated from message anita.v1.PatchUserRequest
 */
export type PatchUserRequest = Message<"anita.v1.PatchUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message anita.v1.PatchUserRequest.
 * Use `create(PatchUserRequestSchema)` to create a new message.
 */
export const PatchUserRequestSchema: GenMessage<PatchUserRequest> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 7);

/**
 * @generated from message anita.v1.PatchUserResponse
 */
export type PatchUserResponse = Message<"anita.v1.PatchUserResponse"> & {
  /**
   * @generated from field: anita.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message anita.v1.PatchUserResponse.
 * Use `create(PatchUserResponseSchema)` to create a new message.
 */
export const PatchUserResponseSchema: GenMessage<PatchUserResponse> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 8);

/**
 * @generated from message anita.v1.DeleteUserRequest
 */
export type DeleteUserRequest = Message<"anita.v1.DeleteUserRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message anita.v1.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export const DeleteUserRequestSchema: GenMessage<DeleteUserRequest> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 9);

/**
 * @generated from message anita.v1.DeleteUserResponse
 */
export type DeleteUserResponse = Message<"anita.v1.DeleteUserResponse"> & {
};

/**
 * Describes the message anita.v1.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export const DeleteUserResponseSchema: GenMessage<DeleteUserResponse> = /*@__PURE__*/
  messageDesc(file_anita_v1_user, 10);

/**
 * @generated from service anita.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc anita.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc anita.v1.UserService.GetUsers
   */
  getUsers: {
    methodKind: "unary";
    input: typeof GetUsersRequestSchema;
    output: typeof GetUsersResponseSchema;
  },
  /**
   * @generated from rpc anita.v1.UserService.PostUser
   */
  postUser: {
    methodKind: "unary";
    input: typeof PostUserRequestSchema;
    output: typeof PostUserResponseSchema;
  },
  /**
   * @generated from rpc anita.v1.UserService.PatchUser
   */
  patchUser: {
    methodKind: "unary";
    input: typeof PatchUserRequestSchema;
    output: typeof PatchUserResponseSchema;
  },
  /**
   * @generated from rpc anita.v1.UserService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof DeleteUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_anita_v1_user, 0);

