// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts,import_extension=none"
// @generated from file admin/v1/rule.proto (package admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRuleRequest, GetRuleResponse, PatchRuleRequest, PatchRuleResponse } from "./rule_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service admin.v1.RuleService
 */
export const RuleService = {
  typeName: "admin.v1.RuleService",
  methods: {
    /**
     * @generated from rpc admin.v1.RuleService.GetRule
     */
    getRule: {
      name: "GetRule",
      I: GetRuleRequest,
      O: GetRuleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc admin.v1.RuleService.PatchRule
     */
    patchRule: {
      name: "PatchRule",
      I: PatchRuleRequest,
      O: PatchRuleResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

