// @generated by protoc-gen-connect-query v1.2.0 with parameter "target=ts,import_extension=none"
// @generated from file admin/v1/schedule.proto (package admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { DeleteScheduleRequest, DeleteScheduleResponse, GetSchedulesRequest, GetSchedulesResponse, PatchScheduleRequest, PatchScheduleResponse, PostScheduleRequest, PostScheduleResponse } from "./schedule_pb";

/**
 * @generated from rpc admin.v1.ScheduleService.GetSchedules
 */
export const getSchedules = {
  localName: "getSchedules",
  name: "GetSchedules",
  kind: MethodKind.Unary,
  I: GetSchedulesRequest,
  O: GetSchedulesResponse,
  service: {
    typeName: "admin.v1.ScheduleService"
  }
} as const;

/**
 * @generated from rpc admin.v1.ScheduleService.PatchSchedule
 */
export const patchSchedule = {
  localName: "patchSchedule",
  name: "PatchSchedule",
  kind: MethodKind.Unary,
  I: PatchScheduleRequest,
  O: PatchScheduleResponse,
  service: {
    typeName: "admin.v1.ScheduleService"
  }
} as const;

/**
 * @generated from rpc admin.v1.ScheduleService.PostSchedule
 */
export const postSchedule = {
  localName: "postSchedule",
  name: "PostSchedule",
  kind: MethodKind.Unary,
  I: PostScheduleRequest,
  O: PostScheduleResponse,
  service: {
    typeName: "admin.v1.ScheduleService"
  }
} as const;

/**
 * @generated from rpc admin.v1.ScheduleService.DeleteSchedule
 */
export const deleteSchedule = {
  localName: "deleteSchedule",
  name: "DeleteSchedule",
  kind: MethodKind.Unary,
  I: DeleteScheduleRequest,
  O: DeleteScheduleResponse,
  service: {
    typeName: "admin.v1.ScheduleService"
  }
} as const;
