name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - frontend/**
      - .github/actions/setup-node/**
  pull_request:
    paths:
      - frontend/**
      - .github/actions/setup-node/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Lint
        run: pnpm run ci:lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Test
        run: pnpm run ci:test
  docker:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Frontend Image
        uses: docker/bake-action@v7
        with:
          source: .
          files: docker-bake.hcl
          targets: frontend
