name: On Push Main

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Build Backend
    uses: ./.github/workflows/wf-docker-build.yaml
    with:
      target: backend
      push-ghcr: true
      save-cache: true
  frontend:
    name: Build Frontend
    uses: ./.github/workflows/wf-docker-build.yaml
    with:
      target: frontend
      push-ghcr: true
      save-cache: true

  promote:
    name: Deploy to Dev
    needs: [backend, frontend]
    uses: ./.github/workflows/wf-promote.yaml
    with:
      environment: dev
      tag: sha-${{ github.sha }}
    secrets: inherit
