name: On Push Main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/wf-docker-build.yaml
    with:
      push-ghcr: true
      save-cache: true

  lint-backend:
    uses: ./.github/workflows/wf-lint-backend.yaml
