name: On Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/wf-docker-build.yaml
    with:
      push-ghcr: false
      save-cache: false

  lint:
    name: Lint
    needs:
      - lint-backend
    runs-on: ubuntu-latest
    steps:
      - run: echo

  lint-backend:
    uses: ./.github/workflows/wf-lint-backend.yaml
