name: On Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/wf-docker-build.yaml
    with:
      push-ghcr: true
      save-cache: false
      update-image: true
    secrets:
      github-app-id: ${{ secrets.PUSHER_APP_ID }}
      github-app-private-key: ${{ secrets.PUSHER_PRIVATE_KEY }}
