name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run Spell Check
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: US
          exclude: |
            Dockerfile
            *.svg
            ./backend/internal/transport/api/api.gen.go
            ./backend/openapi.json
            package.json
            ./frontend/pnpm-lock.yaml
            ./frontend/bun.lock
            ./frontend/packages/api/src/schema.d.ts
            ./backend/.golangci.yaml
            **/go.mod
            **/go.sum
